'use client';
import {useEffect,useRef,useState} from 'react';
const snippets:Record<string,string>={'Beautiful UI':'<AIInterfacePattern />','beUI':'<AgentStatus state="working" />','Rare UI':'<MotionPattern />','Transitions.dev':'<motion.div layout />','shadcn/ui':'<AccessiblePrimitive />','EasyUI':'/* EasyUI · MIT · Suraj Maurya */\n<MotionPrimitive />','Ayodhya Mohanthy':'# AI-native product pattern'};
function kindFor(name:string){const n=name.toLowerCase();if(/load|status|progress|task|thinking|stream|agent|tool/.test(n))return'progress';if(/approval|human|selection|action/.test(n))return'approval';if(/command|search|input|conversation|code/.test(n))return'command';if(/nav|sidebar|dock|menu|tabs/.test(n))return'nav';if(/dialog|sheet|tooltip|reveal/.test(n))return'dialog';if(/table|context|card|grid|insight/.test(n))return'cards';if(/transition|motion|orb|fluid|bounce|scroll|magnetic|morph|ripple/.test(n))return'motion';if(/form|accordion|faq/.test(n))return'form';if(/toast|notification|feedback|failure|eval/.test(n))return'feedback';return'artifact'}
function Demo({name}:{name:string}){const n=name.toLowerCase(),k=kindFor(name),[choice,setChoice]=useState(''),[tab,setTab]=useState(0),[query,setQuery]=useState(''),[level,setLevel]=useState(55),[open,setOpen]=useState(false);const stop=(e:React.SyntheticEvent)=>e.stopPropagation();
if(n.includes('stream'))return <div className="cp cp-stream"><span>Designing</span><p>Evidence should remain visible while the answer <i>takes shape.</i></p><b/></div>;
if(n.includes('tool chips'))return <div className="cp cp-tools">{['Search','Read','Compare','Cite'].map((x,i)=><span key={x}><i>{i<3?'✓':'•'}</i>{x}</span>)}</div>;
if(n.includes('task rows'))return <div className="cp cp-tasks">{['Collect evidence','Check boundary','Prepare review'].map((x,i)=><p key={x}><i>{i<2?'✓':'↻'}</i>{x}<em>{i<2?'done':'active'}</em></p>)}</div>;
if(n.includes('grid reveal'))return <div className="cp cp-grid">{Array.from({length:16},(_,i)=><i key={i}/>)}</div>;
if(n.includes('step player'))return <div className="cp cp-steps" onClick={stop}>{['Observe','Frame','Test'].map((x,i)=><button className={tab===i?'on':''} onClick={()=>setTab(i)} key={x}>0{i+1}</button>)}<p>{['Collect the signal','Choose the problem','Test the risky part'][tab]}</p></div>;
if(n.includes('code block'))return <pre className="cp cp-code"><i>const</i> decision = {'{'}\n  evidence: <b>true</b>,\n  reversible: <b>true</b>\n{'}'}</pre>;
if(n.includes('scroll progress'))return <div className="cp cp-scroll"><i/><span>01</span><span>02</span><span>03</span><b>Keep context while moving</b></div>;
if(n.includes('enter / exit'))return <div className="cp cp-enter"><i/><i/><span>old</span><b>new</b></div>;
if(n.includes('shared layout'))return <div className="cp cp-shared"><i/><i/><b>One object. Two states.</b></div>;
if(n.includes('list transition'))return <div className="cp cp-list">{['A','B','C'].map(x=><p key={x}>{x}<i/></p>)}</div>;
if(n==='tabs')return <div className="cp cp-tabs" onClick={stop}>{['Evidence','Decision','Outcome'].map((x,i)=><button className={tab===i?'on':''} onClick={()=>setTab(i)} key={x}>{x}</button>)}<i style={{transform:`translateX(${tab*82}px)`}}/><p>{['Sources attached','Tradeoff chosen','Result visible'][tab]}</p></div>;
if(n==='sheet')return <div className="cp cp-sheet"><div/><i><span>Review panel</span><b>Confirm boundary</b></i></div>;
if(n==='table')return <div className="cp cp-table">{['Source','Signal','Confidence'].map(x=><b key={x}>{x}</b>)}{Array.from({length:6},(_,i)=><span key={i}/>)}</div>;
if(n==='tooltip')return <div className="cp cp-tooltip" onClick={stop}><button onClick={()=>setOpen(!open)}>Why?</button>{open&&<span>Show context without leaving the task.</span>}</div>;
if(n.includes('20 live'))return <div className="cp cp-lab">{Array.from({length:9},(_,i)=><i key={i}/>) }<span>20 working patterns</span></div>;
if(n.includes('evidence content'))return <div className="cp cp-evidence"><blockquote>“Design claim”</blockquote><a>Source 01 ↗</a><a>Source 02 ↗</a></div>;
if(n.includes('failure taxonomy'))return <div className="cp cp-failure"><span>Recoverable</span><span>Needs review</span><span>Stop</span></div>;
if(n.includes('eval rubric'))return <div className="cp cp-rubric">{['Grounded','Clear','Safe'].map((x,i)=><p key={x}>{x}<i style={{width:`${82-i*17}%`}}/></p>)}</div>;
if(n.includes('handoff'))return <div className="cp cp-handoff"><span>Design</span><i>→</i><span>Build</span><i>→</i><span>Verify</span></div>;
if(k==='progress')return <div className="cp cp-progress"><i/><div><b>Working</b><span>Checking evidence</span></div><section><em/><em/><em/><em/></section></div>;
if(k==='approval')return <div className="cp cp-approval" onClick={stop}><span>Review before action</span><b>{choice?`${choice} selected`:'Ready to publish?'}</b><div><button onClick={()=>setChoice('Hold')}>Hold</button><button onClick={()=>setChoice('Approved')}>Approve</button></div></div>;
if(k==='command')return <div className="cp cp-command" onClick={stop}><div>⌘K <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a pattern…"/></div>{['Find evidence','Open decision','Compare states'].filter(x=>x.toLowerCase().includes(query.toLowerCase())).map(x=><p key={x}><i/>{x}</p>)}</div>;
if(k==='nav')return <div className="cp cp-nav" onClick={stop}>{['Explore','Decide','Ship'].map((x,i)=><button className={tab===i?'on':''} onMouseEnter={()=>setTab(i)} onClick={()=>setTab(i)} key={x}><i>0{i+1}</i>{x}</button>)}<em style={{transform:`translateY(${tab*39}px)`}}/></div>;
if(k==='dialog')return <div className="cp cp-dialog"><div><span>Pattern detail</span><b>Keep context</b><p>Continuity without losing place.</p><button>Done</button></div></div>;
if(k==='cards')return <div className="cp cp-cards"><div>{[1,2,3].map(i=><p key={i}><i/><span>{i===1?'Source':i===2?'Signal':'Decision'}</span></p>)}</div></div>;
if(k==='motion')return <div className="cp cp-motion interactive-motion" onClick={stop}><i style={{transform:`translateX(${(level-50)*1.5}px) rotate(${level*2}deg)`}}/><i/><i/><input aria-label="Motion amount" type="range" min="0" max="100" value={level} onChange={e=>setLevel(+e.target.value)}/><span>Drag to shape motion · {level}%</span></div>;
if(k==='form')return <div className="cp cp-form" onClick={stop}><label>Goal<input defaultValue="Make behaviour clear"/></label><label>Boundary<input defaultValue="Ask before action"/></label></div>;
if(k==='feedback')return <div className="cp cp-feedback"><div><i/>Evidence found</div><div><i/>Boundary checked</div><div><i/>Ready to review</div></div>;
return <div className="cp cp-artifact"><span>PRODUCT DESIGN ARTIFACT</span><p><i/>Intent</p><p><i/>Evidence</p><p><i/>Exit condition</p></div>}
export default function ResourcePreview({source,mode,url,pattern}:{source:string,mode:string,url:string,pattern?:string}){const ref=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false),[copied,setCopied]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{rootMargin:'120px'});io.observe(el);return()=>io.disconnect()},[]);const hosted=mode.startsWith('Hosted'),name=pattern||source;const copy=async()=>{await navigator.clipboard.writeText(`${snippets[source]||snippets['Ayodhya Mohanthy']}\n// ${name}`);setCopied(true);setTimeout(()=>setCopied(false),1500)};return <div ref={ref} className={`resource-preview ${hosted?'live':'link-only'} ${visible?'is-visible':'is-paused'}`}>{hosted?<><Demo name={name}/><details className="preview-code"><summary>Use this pattern <span>+</span></summary><div><button onClick={e=>{e.stopPropagation();copy()}}>{copied?'Copied ✓':'Copy starter code'}</button><a onClick={e=>e.stopPropagation()} href={url}>View source ↗</a></div></details></>:<><div className="external-preview"><i>↗</i><span>LINK-ONLY REFERENCE</span><b>{name}</b><p>Explore this restricted set at its creator&apos;s site.</p></div><a onClick={e=>e.stopPropagation()} className="source-cta" href={url}>See it at the source ↗</a></>}</div>}
