'use client';
import {useEffect,useState} from 'react';
import {PixelLoader,SegmentedTrace,StreamText} from './vendor/beautiful-ui/Primitives';

const tasks=[['Evidence gathered','done'],['Contradictions checked','done'],['Recommendation drafted','active'],['Human approval','waiting']];
export default function AIInterfaceLab(){
 const [run,setRun]=useState(0),[approved,setApproved]=useState<'idle'|'yes'|'no'>('idle'),[query,setQuery]=useState('Show the strongest healthcare outcome'),[confidence,setConfidence]=useState(72),[selected,setSelected]=useState('Clinical Trial Tool'),[command,setCommand]=useState(''),[nav,setNav]=useState('Evidence'),[codeView,setCodeView]=useState<'source'|'diff'>('source'),[fine,setFine]=useState(64),[selection,setSelection]=useState(''),[insight,setInsight]=useState(1);
 useEffect(()=>{const id=setInterval(()=>setRun(x=>x+1),8000);return()=>clearInterval(id)},[]);
 return <div className="native-lab">
  <div className="lab-toolbar"><div><PixelLoader label="Interface lab running"/><span>20 live patterns · local only</span></div><button onClick={()=>setRun(x=>x+1)}>Replay motion</button></div>
  <div className="lab-grid">
   <section className="lab-card lab-wide"><div className="lab-label"><span>01</span>Streaming answer</div><h3 key={run}><StreamText run>Clinical Trial Tool carries the strongest published healthcare outcome: the case reports a 40% streamlined workflow and 90% user satisfaction.</StreamText></h3><div className="source-chip">Source attached · native case study</div></section>
   <section className="lab-card"><div className="lab-label"><span>02</span>Reasoning trace</div><SegmentedTrace items={[{label:'Plan',content:'Match the question to case tags and outcome claims.'},{label:'Evidence',content:'Clinical Trial Tool · healthcare · three published outcome claims.'},{label:'Limits',content:'Claims are reproduced from the published case, not independently verified.'}]}/></section>
   <section className="lab-card"><div className="lab-label"><span>03</span>Human approval</div><p className="lab-question">Use the case-study claim in a recruiter summary?</p><div className="approval-facts"><span>Action</span><b>Publish claim</b><span>Risk</span><b>Needs source label</b></div>{approved==='idle'?<div className="lab-actions"><button onClick={()=>setApproved('no')}>Hold</button><button className="primary" onClick={()=>setApproved('yes')}>Approve with label</button></div>:<button className="reset" onClick={()=>setApproved('idle')}>{approved==='yes'?'Approved with source visible':'Held for review'} · reset</button>}</section>
   <section className="lab-card"><div className="lab-label"><span>04</span>Agent task state</div><div className="task-stack">{tasks.map(([label,state],i)=><div className={state} key={label}><i>{state==='done'?'✓':state==='active'?'↻':'·'}</i><span>{label}</span><em>{state}</em></div>)}</div></section>
   <section className="lab-card"><div className="lab-label"><span>05</span>Prompt contract</div><div className="contract"><div><span>Goal</span><b>Find decision-ready evidence</b></div><div><span>Must</span><b>Show source and limit</b></div><div><span>Never</span><b>Invent experience</b></div></div></section>
   <section className="lab-card lab-wide"><div className="lab-label"><span>06</span>Intent composer</div><div className="prompt-box"><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Try a portfolio question"/><button onClick={()=>setRun(x=>x+1)}>Run</button></div><div className="tool-chips"><span>search_cases</span><span>rank_evidence</span><span>attach_sources</span></div></section>
   <section className="lab-card"><div className="lab-label"><span>07</span>Confidence control</div><div className="confidence"><b>{confidence}%</b><span>{confidence>80?'High confidence':confidence>55?'Review recommended':'Human decision required'}</span><input type="range" min="20" max="95" value={confidence} onChange={e=>setConfidence(+e.target.value)}/></div></section>
   <section className="lab-card"><div className="lab-label"><span>08</span>Recommendation</div><div className="reco"><span>Best evidence match</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option>Clinical Trial Tool</option><option>Application Automation</option><option>Orbit</option></select><p>{selected==='Clinical Trial Tool'?'Healthcare depth + quantified outcome claims.':selected==='Application Automation'?'Enterprise workflow + business outcome claims.':'AI-native product thinking + visible accountability.'}</p></div></section>
   <section className="lab-card"><div className="lab-label"><span>09</span>Before / after</div><div className="diff"><del>AI gives one opaque answer</del><ins>AI shows answer + evidence + limits</ins></div></section>
   <section className="lab-card"><div className="lab-label"><span>10</span>Escalation rule</div><div className="escalation"><span>If confidence &lt; 60%</span><b>Stop before action</b><p>Show the unresolved choice to a person with the evidence already gathered.</p></div></section>
   <section className="lab-card"><div className="lab-label"><span>11</span>Loading state</div><div className="full-loader" key={run}>{Array.from({length:45},(_,i)=><i key={i} style={{animationDelay:`${i*26}ms`}}/>)}<p><b>Retrieving evidence</b><span>2.4s</span></p></div></section>
   <section className="lab-card"><div className="lab-label"><span>12</span>Tool chips</div><div className="tool-run"><div><span className="done">✓ search_cases</span><em>7 results</em></div><div><span className="done">✓ rank_evidence</span><em>32ms</em></div><div><span className="running">↻ attach_sources</span><em>running</em></div></div></section>
   <section className="lab-card lab-wide"><div className="lab-label"><span>13</span>Context cards</div><div className="context-grid">{[['Clinical Trial Tool','Healthcare operations','40% workflow streamlined'],['Application Automation','Enterprise SaaS','40% faster setup'],['Orbit','AI-native concept','Human owns the decision']].map(x=><article key={x[0]}><span>{x[1]}</span><b>{x[0]}</b><p>{x[2]}</p><em>Native case study ↗</em></article>)}</div></section>
   <section className="lab-card"><div className="lab-label"><span>14</span>Sidebar nav</div><div className="mini-sidebar">{['Evidence','Decisions','Outcomes','Sources'].map((x,i)=><button className={nav===x?'on':''} onMouseEnter={()=>setNav(x)} onFocus={()=>setNav(x)} onClick={()=>setNav(x)} key={x}><span>0{i+1}</span>{x}</button>)}<i style={{transform:`translateY(${['Evidence','Decisions','Outcomes','Sources'].indexOf(nav)*42}px)`}}/></div></section>
   <section className="lab-card"><div className="lab-label"><span>15</span>Command search</div><div className="command-palette"><div><kbd>⌘K</kbd><input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Search the system…"/></div>{['Open evidence library','Compare case outcomes','Review AI process','Inspect source trail'].filter(x=>x.toLowerCase().includes(command.toLowerCase())).map((x,i)=><button key={x}><span>0{i+1}</span>{x}<kbd>↵</kbd></button>)}{!['Open evidence library','Compare case outcomes','Review AI process','Inspect source trail'].some(x=>x.toLowerCase().includes(command.toLowerCase()))&&<p>No matching command</p>}</div></section>
   <section className="lab-card lab-wide"><div className="lab-label"><span>16</span>Flowchart</div><div className="flow-demo"><div><b>User intent</b><span>typed or selected</span></div><i>→</i><div><b>Retrieve</b><span>local case index</span></div><i>→</i><div><b>Check</b><span>source + limit</span></div><i>→</i><div className="accent"><b>Show answer</b><span>with evidence</span></div></div></section>
   <section className="lab-card"><div className="lab-label"><span>17</span>Insight cards</div><div className="insight-card"><span>0{insight+1} / 03</span><b>{['Evidence before interface','Approval at the risk boundary','Uncertainty needs a next move'][insight]}</b><svg viewBox="0 0 240 70" role="img" aria-label="Interactive trend line"><path d={['M5 58 C45 50 60 55 90 38 S150 30 235 12','M5 54 C50 58 70 24 110 40 S170 16 235 22','M5 60 C45 18 75 54 120 24 S190 45 235 10'][insight]}/></svg><div>{[0,1,2].map(i=><button aria-label={`Show insight ${i+1}`} className={insight===i?'on':''} onClick={()=>setInsight(i)} key={i}/>)}</div></div></section>
   <section className="lab-card"><div className="lab-label"><span>18</span>Code block</div><div className="code-tabs"><button className={codeView==='source'?'on':''} onClick={()=>setCodeView('source')}>Source</button><button className={codeView==='diff'?'on':''} onClick={()=>setCodeView('diff')}>Diff</button></div><pre className="code-block">{codeView==='source'?`01  const answer = retrieve(intent)
02  return attachSources(answer)
03  // never invent experience`:`+ showSource(claim)
+ showLimit(answer)
- return opaqueOutput`}</pre></section>
   <section className="lab-card"><div className="lab-label"><span>19</span>Fine-tune card</div><div className="fine-card"><div><span>Answer confidence</span><b>{fine}%</b></div><input type="range" min="20" max="95" value={fine} onChange={e=>setFine(+e.target.value)}/><div className="fine-preview" style={{opacity:.45+fine/180}}>Evidence is visible. Human judgment stays in control.</div></div></section>
   <section className="lab-card lab-wide"><div className="lab-label"><span>20</span>Selection actions</div><div className="selection-demo"><p><mark>AI proposes alternatives</mark>, but the designer verifies the evidence, chooses the direction and owns the recommendation.</p><div><button onClick={()=>setSelection('Made more direct')}>Rewrite</button><button onClick={()=>setSelection('Key claim saved')}>Save insight</button><button onClick={()=>setSelection('Source check attached')}>Add source</button></div>{selection&&<span>{selection} ✓</span>}</div></section>
  </div>
 </div>
}
