export type Territory={id:string;label:string};
export type AtlasNode={id:string;label:string;territory:string;kind:'Pattern'|'Template'|'Case';href:string;note:string};
export type AtlasEdge={from:string;to:string;rel:'pairs-with'|'mitigates'|'feeds-into'};
export type FieldNote={date:string;title:string;body:string;source:{label:string;url:string};nodes:string[]};

export const territories:Territory[]=[
{id:'conversation',label:'Conversation'},
{id:'agent-state',label:'Agent state'},
{id:'human-control',label:'Human control'},
{id:'tools',label:'Tools'},
{id:'grounding',label:'Grounding'},
{id:'navigation',label:'Navigation'},
{id:'evaluation',label:'Evaluation'},
{id:'failure',label:'Failure'},
{id:'process',label:'Process'}];

export const atlasNodes:AtlasNode[]=[
{id:'thread',label:'Thread',territory:'conversation',kind:'Pattern',href:'/resources',note:'The container: messages, composer, auto-scroll, accessibility.'},
{id:'composer',label:'Composer',territory:'conversation',kind:'Pattern',href:'/resources',note:'Input is a surface, not a text box: attachments, commands, models.'},
{id:'conversation-map',label:'Conversation map',territory:'conversation',kind:'Pattern',href:'/resources',note:'One tick per turn, viewport marked. The map chat never shipped.'},
{id:'streaming-text',label:'Streaming text',territory:'conversation',kind:'Pattern',href:'/resources',note:'Tokens land softly; evidence stays visible while the answer forms.'},
{id:'branch-picker',label:'Branch picker',territory:'conversation',kind:'Pattern',href:'/resources',note:'Edits create branches; the user picks which line continues.'},
{id:'attachment',label:'Attachment',territory:'conversation',kind:'Pattern',href:'/resources',note:'Files stage inside the composer with per-file progress.'},
{id:'plan-tool',label:'Plan tool',territory:'agent-state',kind:'Pattern',href:'/resources',note:'The plan is a visible checklist, not hidden reasoning.'},
{id:'subagent-handoff',label:'Subagent handoff',territory:'agent-state',kind:'Pattern',href:'/resources',note:'Delegation is shown with what moved and why.'},
{id:'agent-thinking',label:'Agent thinking',territory:'agent-state',kind:'Pattern',href:'/resources',note:'A status line that names the work, with elapsed time.'},
{id:'task-rows',label:'Task rows',territory:'agent-state',kind:'Pattern',href:'/resources',note:'Done, active, queued - the work list as interface.'},
{id:'model-downloader',label:'Model downloader',territory:'agent-state',kind:'Pattern',href:'/resources',note:'On-device starts here: size, progress, offline cache.'},
{id:'context-usage-meter',label:'Context usage meter',territory:'agent-state',kind:'Pattern',href:'/resources',note:'The token budget as a segmented, legible meter.'},
{id:'storage-meter',label:'Storage meter',territory:'agent-state',kind:'Pattern',href:'/resources',note:'Quota with the eviction rule stated before it bites.'},
{id:'loading-state',label:'Loading state',territory:'agent-state',kind:'Pattern',href:'/resources',note:'Progress that names what is happening, not a spinner.'},
{id:'thinking-trace',label:'Thinking trace',territory:'agent-state',kind:'Pattern',href:'/resources',note:'Reasoning exposed in segments, with limits attached.'},
{id:'clarifying-question',label:'Clarifying question',territory:'human-control',kind:'Pattern',href:'/resources',note:'The agent asks before acting; the answer sets scope.'},
{id:'reviewed-edit',label:'Reviewed edit',territory:'human-control',kind:'Pattern',href:'/resources',note:'A proposed change with accept and reject as equals.'},
{id:'approval-card',label:'Approval card',territory:'human-control',kind:'Pattern',href:'/resources',note:'Says what approval changes before asking for it.'},
{id:'capability-gate',label:'Capability gate',territory:'human-control',kind:'Pattern',href:'/resources',note:'Checks the device before promising on-device anything.'},
{id:'selection-actions',label:'Selection actions',territory:'human-control',kind:'Pattern',href:'/resources',note:'Act on a selection: rewrite, save, attach a source.'},
{id:'message-actions',label:'Message actions',territory:'human-control',kind:'Pattern',href:'/resources',note:'Per-message control: copy, retry, branch, flag.'},
{id:'mcp-tool',label:'MCP tool',territory:'tools',kind:'Pattern',href:'/resources',note:'A server call with request, result and receipt visible.'},
{id:'tool-fallback',label:'Tool fallback',territory:'tools',kind:'Pattern',href:'/resources',note:'The default renderer for calls with no dedicated UI.'},
{id:'tool-chips',label:'Tool chips',territory:'tools',kind:'Pattern',href:'/resources',note:'Which tools ran, in order, with status.'},
{id:'web-search',label:'Web search',territory:'tools',kind:'Pattern',href:'/resources',note:'The research trail: queries run and sources opened, drawn live.'},
{id:'context-cards',label:'Context cards',territory:'grounding',kind:'Pattern',href:'/resources',note:'Evidence as objects with source and limit beside the claim.'},
{id:'insight-cards',label:'Insight cards',territory:'grounding',kind:'Pattern',href:'/resources',note:'A finding with its trend line and a way to step through.'},
{id:'command-search',label:'Command search',territory:'navigation',kind:'Pattern',href:'/resources',note:'The whole system behind one keystroke, grouped by action.'},
{id:'sidebar-nav',label:'Sidebar nav',territory:'navigation',kind:'Pattern',href:'/resources',note:'Section wayfinding with the position marker sliding.'},
{id:'eval-rubric',label:'Eval rubric',territory:'evaluation',kind:'Template',href:'/library',note:'Score the answer before the user does: grounded, clear, safe.'},
{id:'error-recovery',label:'Error recovery',territory:'failure',kind:'Pattern',href:'/resources',note:'A quiet failure with a retry that does not restart the turn.'},
{id:'failure-taxonomy',label:'Failure taxonomy',territory:'failure',kind:'Template',href:'/library',note:'Recoverable, needs review, stop - named before they happen.'},
{id:'capability-brief',label:'Capability + boundary brief',territory:'process',kind:'Template',href:'/library',note:'What the system can do, where it breaks, what it must never imply.'},
{id:'approval-matrix',label:'Approval matrix',territory:'process',kind:'Template',href:'/library',note:'Which actions need a human, and what approval changes.'},
{id:'handoff-rule',label:'Handoff rule',territory:'process',kind:'Template',href:'/library',note:'When work moves between agents, what travels with it.'},
{id:'clinical-trial-tool',label:'Clinical Trial Tool',territory:'grounding',kind:'Case',href:'/work/clinical-trial-tool',note:'Evidence-first design under healthcare scrutiny.'},
{id:'application-automation',label:'Application Automation',territory:'tools',kind:'Case',href:'/work/application-automation',note:'Tool calls and approvals in a shipped enterprise flow.'}];

export const atlasEdges:AtlasEdge[]=[
{from:'conversation-map',to:'thread',rel:'pairs-with'},
{from:'branch-picker',to:'conversation-map',rel:'pairs-with'},
{from:'composer',to:'attachment',rel:'pairs-with'},
{from:'composer',to:'command-search',rel:'pairs-with'},
{from:'streaming-text',to:'agent-thinking',rel:'pairs-with'},
{from:'clarifying-question',to:'error-recovery',rel:'mitigates'},
{from:'capability-brief',to:'capability-gate',rel:'feeds-into'},
{from:'capability-gate',to:'model-downloader',rel:'feeds-into'},
{from:'context-usage-meter',to:'storage-meter',rel:'pairs-with'},
{from:'model-downloader',to:'storage-meter',rel:'feeds-into'},
{from:'mcp-tool',to:'tool-fallback',rel:'feeds-into'},
{from:'tool-chips',to:'mcp-tool',rel:'pairs-with'},
{from:'web-search',to:'context-cards',rel:'feeds-into'},
{from:'plan-tool',to:'subagent-handoff',rel:'feeds-into'},
{from:'task-rows',to:'plan-tool',rel:'pairs-with'},
{from:'handoff-rule',to:'subagent-handoff',rel:'feeds-into'},
{from:'approval-matrix',to:'reviewed-edit',rel:'feeds-into'},
{from:'approval-matrix',to:'approval-card',rel:'feeds-into'},
{from:'reviewed-edit',to:'message-actions',rel:'pairs-with'},
{from:'failure-taxonomy',to:'error-recovery',rel:'feeds-into'},
{from:'eval-rubric',to:'insight-cards',rel:'feeds-into'},
{from:'loading-state',to:'agent-thinking',rel:'feeds-into'},
{from:'thinking-trace',to:'plan-tool',rel:'pairs-with'},
{from:'sidebar-nav',to:'conversation-map',rel:'pairs-with'},
{from:'clinical-trial-tool',to:'context-cards',rel:'feeds-into'},
{from:'application-automation',to:'mcp-tool',rel:'feeds-into'},
{from:'selection-actions',to:'message-actions',rel:'pairs-with'}];

export const fieldNotes:FieldNote[]=[
{date:'06 Sep 2026',title:'The interface starts before the model',body:'LocalMode UI gets the order right: capability gate first, download bar second, budget meters after that. Most on-device AI fails as a promise before it fails as a product. Checking what the device can do is an interface decision, not an engineering detail.',source:{label:'LocalMode UI',url:'https://localmode.ai/docs/local-first/capability-gate'},nodes:['capability-gate','model-downloader','context-usage-meter','storage-meter']},
{date:'05 Sep 2026',title:'Honest motion is a research trail',body:'Most streaming UI fakes liveness with shimmer. BoardUI\u2019s web search draws each source as it opens - the motion is the evidence arriving, not decoration over a wait. That is the difference between animation as progress and animation as theater.',source:{label:'BoardUI',url:'https://www.boardui.com/components/web-search'},nodes:['web-search','agent-thinking','context-cards']},
{date:'03 Sep 2026',title:'Chat has scrollbars but no map',body:'assistant-ui\u2019s conversation map is the pattern long threads were missing: one tick per turn, the viewport marked, jump by tapping. Scroll position is not navigation. Every long agent thread I design from here gets a map.',source:{label:'assistant-ui',url:'https://www.assistant-ui.com/docs'},nodes:['conversation-map','thread','branch-picker']},
{date:'03 Sep 2026',title:'Workflow states are components now',body:'Agent Elements ships the states I used to draw by hand: the clarifying question, the reviewed edit, the plan, the handoff, the recoverable error. When a pattern becomes a component, it stops being a nice-to-have and starts being a floor.',source:{label:'Agent Elements',url:'https://agent-elements.21st.dev/docs'},nodes:['clarifying-question','reviewed-edit','plan-tool','subagent-handoff','mcp-tool','error-recovery']},
{date:'30 Aug 2026',title:'The base layer settled',body:'Six assistant-ui primitives now cover the chat skeleton: thread, composer, tool fallback, branching, attachments, message actions. The interesting design work has moved up a level - to approval, evidence and recovery. That is where this atlas concentrates.',source:{label:'assistant-ui',url:'https://www.assistant-ui.com/docs'},nodes:['thread','composer','tool-fallback','branch-picker','attachment','message-actions']},
{date:'29 Aug 2026',title:'Approval is a content problem, not a modal',body:'A modal that says "Are you sure?" teaches nothing. An approval that names the action, the risk and what changes earns its interruption. Every approval surface in my interface lab now answers those three questions before it asks one.',source:{label:'Interface lab',url:'/work/ai-interface-exploration'},nodes:['approval-card','reviewed-edit','approval-matrix']}];
