import Image from 'next/image';
import Link from 'next/link';
import sourceCases from './behanceCaseData.json';
import type {Case} from './data';

type SourceCase=(typeof sourceCases)[number];
const headings=/^(\d+\.?\s*)?(challenge|background|overview|my role|product details|ux approach|research|discovery|definition|ideation|design|solution|outcome|impact|methodology|current state|business objectives|user|stakeholder|hypothesis|prioritisation|narrowing|results|process|testing|audit|insight|what|why|key|proposed|digital|findings)/i;
function sections(lines:string[]){const out:{title:string;body:string[]}[]=[];let cur={title:'Project context',body:[] as string[]};for(const line of lines){const short=line.length<76;const isHead=(short&&(headings.test(line)||line.endsWith(':')||line===line.toUpperCase()))&&!/^[-•]/.test(line);if(isHead){if(cur.body.length)out.push(cur);cur={title:line.replace(/:$/,''),body:[]}}else cur.body.push(line)}if(cur.body.length)out.push(cur);return out.filter(x=>x.body.length).reduce((a,x)=>{const prev=a[a.length-1];if(prev&&(x.body.length<2||x.title==='‍'||x.title==='Before'||x.title==='After'||/^\d+%$/.test(x.title))){prev.body.push(x.title,...x.body)}else a.push(x);return a},[] as {title:string;body:string[]}[])}
export default function BehanceNativeCase({c}:{c:Case}){const src=sourceCases.find(x=>x.slug===c.slug) as SourceCase|undefined;if(!src)return null;const groups=sections(src.lines),storyGroups=groups.slice(0,12);return <main className="native-case-page"><aside className="native-case-rail"><Link href="/">Ayodhya Mohanthy</Link><div><p>{c.kicker}</p><h1>{c.title}</h1><span>{c.summary}</span><div>{c.category.map(x=><i key={x}>{x}</i>)}</div></div><nav><a href="#story">Read the case ↓</a><a href={src.source}>Original source ↗</a></nav></aside><article className="native-case-story" id="story"><header className={`native-case-hero ${((src.lines[0]||c.challenge).length>72)?'dense':''}`}><div><p>SOURCE-BACKED CASE STUDY</p><h2>{src.lines[0]||c.challenge}</h2>{c.impact.map(x=><b key={x}>{x}</b>)}</div>{src.images[0]&&<Image src={src.images[0].src} alt={src.images[0].alt} width={src.images[0].width||1400} height={src.images[0].height||800} priority/>}</header>{src.thin&&<section className="thin-case-note"><b>Compact source</b><p>The published project contains limited narrative. This native version keeps that boundary visible rather than inventing a full process story.</p></section>}<section className="native-case-flow">{storyGroups.map((g,i)=><section className="native-story-block" key={`${g.title}-${i}`}><div className="native-story-copy"><span>{String(i+1).padStart(2,'0')}</span><h2>{g.title}</h2>{g.body.map((p,j)=><p key={j}>{p}</p>)}</div>{src.images[Math.min(i+1,src.images.length-1)]&&<figure><Image src={src.images[Math.min(i+1,src.images.length-1)].src} alt={src.images[Math.min(i+1,src.images.length-1)].alt} width={src.images[Math.min(i+1,src.images.length-1)].width||1400} height={src.images[Math.min(i+1,src.images.length-1)].height||800}/></figure>}</section>)}</section><section className="native-gallery"><div><p>PROJECT ARTIFACTS</p><h2>The screens and process, brought into the case.</h2></div>{src.images.slice(Math.min(storyGroups.length+1,src.images.length)).map((im,i)=><figure className={i%4===0?'wide':''} key={im.src}><Image src={im.src} alt={im.alt} width={im.width||1400} height={im.height||800}/></figure>)}</section><footer className="native-case-source"><p>Rebuilt natively from Ayodhya’s published project. Claims and process descriptions remain attributed to that source.</p><a href={src.source}>View original source ↗</a><Link href="/">Back to work ↑</Link></footer></article></main>}
