export type Capability={n:number;title:string;status:'Strong evidence'|'Partial evidence'|'Needs evidence';summary:string;proof:{label:string;href:string}[];missing:string[]};
export const capabilities:Capability[]=[
{n:1,title:'Visual foundations',status:'Strong evidence',summary:'The portfolio itself is a working visual system: constrained palette, type scale, spacing rhythm, hierarchy and repeated visual grammar.',proof:[{label:'Live portfolio system',href:'/system'},{label:'Responsive homepage',href:'/'}],missing:['Explicit Gestalt critique','Rationale from a shipped product']},
{n:2,title:'Figma mastery',status:'Needs evidence',summary:'A coded system cannot prove how production files are structured in Figma.',proof:[],missing:['Production Figma file','Variables and modes','Auto layout','Components and variants','Prototype connections','Dev Mode handoff']},
{n:3,title:'UX research',status:'Partial evidence',summary:'Cases describe workflow mapping, mixed evidence and hypothesis framing. The research artifacts are not published yet.',proof:[{label:'Clinical Trial Tool',href:'/work/clinical-trial-tool'},{label:'Data product design',href:'/work/data-product-design'}],missing:['Interview guide and notes','JTBD set','Survey summary','Synthesis board','Usability findings']},
{n:4,title:'Information architecture and flows',status:'Partial evidence',summary:'The portfolio and evidence engine have clear, inspectable flows. Shipped-project flow artifacts are still missing.',proof:[{label:'Portfolio IA',href:'#ia-flow'},{label:'Application Automation',href:'/work/application-automation'}],missing:['Product user flow','Journey map','Early wireframes','Edge-case inventory','Empty-state matrix']},
{n:5,title:'Interaction design and prototyping',status:'Strong evidence',summary:'Twenty live AI interaction patterns show motion, controls, transitions, feedback and recovery.',proof:[{label:'20-pattern interface lab',href:'/work/ai-interface-exploration'}],missing:['Tested production prototype','Real-user findings and iteration']},
{n:6,title:'Design systems',status:'Strong evidence',summary:'The site ships real tokens, shared React primitives, responsive rules, source history and a changelog.',proof:[{label:'Design system documentation',href:'/system'},{label:'Canonical GitHub source',href:'https://github.com/ayodhyamohanthy/ai-portfolio'}],missing:['Figma library architecture','Team contribution model','Adoption evidence']},
{n:7,title:'Accessibility and inclusive design',status:'Partial evidence',summary:'Semantic controls, focus treatment, reduced motion and responsive layouts are implemented. Formal conformance is not claimed.',proof:[{label:'Accessibility statement',href:'/accessibility'}],missing:['WCAG 2.2 audit','Contrast report','Screen-reader test notes','Remediation log']},
{n:8,title:'UX writing and content design',status:'Strong evidence',summary:'The live interface demonstrates action copy, source disclosure, uncertainty, approval, failure and recovery language.',proof:[{label:'Content pattern gallery',href:'/content-patterns'},{label:'Starter kit',href:'/library'}],missing:['Before/after copy from shipped work','Product voice and tone guide']},
{n:9,title:'AI-era UX patterns',status:'Strong evidence',summary:'The strongest body of proof: streaming, latency, tools, sources, reasoning, confidence, approval, escalation and human control.',proof:[{label:'Interactive AI lab',href:'/work/ai-interface-exploration'},{label:'17-artifact starter kit',href:'/library'}],missing:['Observed use in a shipped AI product']},
{n:10,title:'Data-informed design',status:'Partial evidence',summary:'Published case-study outcomes and evidence-led framing are present. The underlying analytics trail is not.',proof:[{label:'Clinical outcome claims',href:'/work/clinical-trial-tool'},{label:'Automation outcome claims',href:'/work/application-automation'}],missing:['Event taxonomy','Funnel analysis','Experiment brief','A/B result','Baseline vs post-release data']},
{n:11,title:'Handoff and collaboration',status:'Partial evidence',summary:'The production codebase, source history and implementation specs show shipping discipline, not yet team collaboration evidence.',proof:[{label:'GitHub source and commits',href:'https://github.com/ayodhyamohanthy/ai-portfolio'},{label:'System documentation',href:'/system'}],missing:['Handoff spec','Acceptance criteria','Design QA log','Engineer feedback','Launch retrospective']},
{n:12,title:'Portfolio and case studies',status:'Partial evidence',summary:'Seven native cases cover B2B SaaS, healthcare, data, telemetry, adtech and AI-native practice. Five still need project-specific artifacts.',proof:[{label:'Case-study index',href:'/#work'},{label:'AI interface case',href:'/work/ai-interface-exploration'}],missing:['Deep artifacts for strongest three cases','Role, team and timeline detail','Original screens','Outcome sources']}
];
