export type ShelfResource={label:string;url:string};
export type AgentDesignSkill={id:string;category:'ai-design-skills';group:string;name:string;publisher:string;type:string;canonicalUrl:string;sourceUrl?:string;status?:string;license?:string;compatibility:string[];capabilities:string[];whyItMatters:string;lesson:string;relatedResources:ShelfResource[];featured:boolean;addedAt:string;lastVerifiedAt:string};
export const agentSkillGroups:Record<string,{label:string;order:number}>={workflow:{label:'Workflow & system skills',order:1},guardrails:{label:'Aesthetic & anti-slop guardrails',order:2},polish:{label:'Interaction & polish',order:3},other:{label:'Other',order:99}};
export const agentDesignSkills:AgentDesignSkill[]=[
{id:'anthropic-frontend-design',category:'ai-design-skills',group:'workflow',name:'Frontend Design',publisher:'Anthropic',type:'Agent skill',canonicalUrl:'https://github.com/anthropics/skills/tree/main/skills/frontend-design',compatibility:['coding agents'],capabilities:['frontend design','visual judgment'],whyItMatters:'The baseline that made visual judgment portable inside a coding-agent workflow.',lesson:'Portable visual judgment',relatedResources:[],featured:true,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'},
{id:'impeccable',category:'ai-design-skills',group:'workflow',name:'Impeccable',publisher:'Paul Bakaus',type:'Agent skill and commands',canonicalUrl:'https://github.com/pbakaus/impeccable',status:'active',license:'Apache-2.0',compatibility:['coding agents'],capabilities:['1 skill','23 commands','61 detector rules'],whyItMatters:'For turning aesthetic critique into explicit commands and detector rules.',lesson:'Taste needs an operational vocabulary',relatedResources:[],featured:true,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'},
{id:'open-design',category:'ai-design-skills',group:'workflow',name:'OpenDesign',publisher:'nexu-io',type:'Local-first design workspace',canonicalUrl:'https://open-design.ai/',sourceUrl:'https://github.com/nexu-io/open-design',status:'active',license:'Apache-2.0',compatibility:['DESIGN.md','local-first'],capabilities:['design context','agent collaboration'],whyItMatters:'For keeping product design context local, legible, and close to the work.',lesson:'Context belongs beside the product',relatedResources:[{label:'Source repository ↗',url:'https://github.com/nexu-io/open-design'}],featured:true,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'},
{id:'ui-ux-pro-max',category:'ai-design-skills',group:'workflow',name:'UI UX Pro Max',publisher:'Next Level Builder',type:'Design reasoning skill',canonicalUrl:'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',status:'v2.0',license:'MIT',compatibility:['coding agents'],capabilities:['192 reasoning rules','119 UX guidelines','74 font pairings'],whyItMatters:'For exposing a wide design reasoning surface an agent can consult before it renders.',lesson:'Breadth still needs product judgment',relatedResources:[],featured:false,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'},
{id:'taste-skill',category:'ai-design-skills',group:'guardrails',name:'Taste Skill',publisher:'Leonxlnx',type:'Aesthetic guardrail',canonicalUrl:'https://www.tasteskill.dev/',sourceUrl:'https://github.com/Leonxlnx/taste-skill',status:'v2 experimental',license:'MIT',compatibility:['frontend agents'],capabilities:['taste constraints','anti-slop critique'],whyItMatters:'For making aesthetic constraints visible before generic interface habits take over.',lesson:'Guardrails before decoration',relatedResources:[{label:'Source repository ↗',url:'https://github.com/Leonxlnx/taste-skill'}],featured:true,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'},
{id:'hallmark',category:'ai-design-skills',group:'guardrails',name:'Hallmark',publisher:'Nutlope',type:'Interface audit skill',canonicalUrl:'https://github.com/Nutlope/hallmark',status:'active',license:'MIT',compatibility:['coding agents'],capabilities:['audit','redesign','review','improve'],whyItMatters:'For giving an agent clear verbs to inspect and improve a rendered interface.',lesson:'Critique must lead to a change',relatedResources:[],featured:false,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'},
{id:'scoville',category:'ai-design-skills',group:'guardrails',name:'Scoville',publisher:'Benjamin Stelzer',type:'Anti-slop skill family',canonicalUrl:'https://github.com/benjaminstelzer/scoville-design-anti-ai-slop',status:'active',license:'MIT',compatibility:['design','UI','code','writing'],capabilities:['design critique','UI critique','code critique','writing critique'],whyItMatters:'For separating visual, implementation, and writing guardrails without pretending they are the same job.',lesson:'Specific critique beats one generic score',relatedResources:[{label:'Scoville UI ↗',url:'https://github.com/benjaminstelzer/scoville-ui-anti-ai-slop'},{label:'Scoville Code ↗',url:'https://github.com/benjaminstelzer/scoville-code-anti-ai-slop'},{label:'Scoville Scribe · writing ↗',url:'https://github.com/benjaminstelzer/scoville-scribe-anti-ai-slop'}],featured:false,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'},
{id:'skills-designers-engineers',category:'ai-design-skills',group:'polish',name:'Skills for Designers and Engineers',publisher:'Emil Kowalski',type:'Interaction skill collection',canonicalUrl:'https://emilkowal.ski/skill',sourceUrl:'https://github.com/emilkowalski/skills',status:'active',license:'MIT',compatibility:['designers','engineers','coding agents'],capabilities:['emil-design-eng','animate','review animations','improve animations','animation vocabulary'],whyItMatters:'For translating interaction craft into a shared vocabulary designers, engineers, and agents can act on.',lesson:'Polish needs shared language',relatedResources:[{label:'Source repository ↗',url:'https://github.com/emilkowalski/skills'}],featured:true,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'}];
export const groupedAgentSkills=()=>Object.entries(Object.groupBy([...agentDesignSkills].sort((a,b)=>Number(b.featured)-Number(a.featured)||b.addedAt.localeCompare(a.addedAt)||a.name.localeCompare(b.name)),x=>x.group)).sort(([a],[b])=>(agentSkillGroups[a]??agentSkillGroups.other).order-(agentSkillGroups[b]??agentSkillGroups.other).order);
export type DesignPerson={id:string;category:'people-in-design';group:string;name:string;role:string;org:string;profileLinks:{label:string;url:string;primary?:boolean}[];topics:string[];whyIFollow:string;whatToStudy:string;featured:boolean;addedAt:string;lastVerifiedAt:string;image?:string};
export const peopleInDesign:DesignPerson[]=[{id:'emil-kowalski',category:'people-in-design',group:'design-engineering',name:'Emil Kowalski',role:'Design Engineer',org:'Linear',profileLinks:[{label:'X',url:'https://x.com/emilkowalski',primary:true},{label:'Website',url:'https://emilkowal.ski/'}],topics:['motion','interaction','design engineering'],whyIFollow:'For the care he brings to how interfaces move, feel, and behave - and for making that judgment legible to designers and engineers.',whatToStudy:'Purposeful motion, timing and easing, interaction detail, and the bridge between design judgment and production code.',featured:true,addedAt:'2026-09-16',lastVerifiedAt:'2026-09-16'}] satisfies DesignPerson[]; peopleInDesign.sort((a,b)=>Number(b.featured)-Number(a.featured)||b.addedAt.localeCompare(a.addedAt)||a.name.localeCompare(b.name));
