export type FreshFind={date:string;title:string;body:string;source:{label:string;url:string};tags:string[]};
export const freshFinds:FreshFind[]=[
{date:'13 Sep 2026',title:'Our eukaryotic moment',body:'Venkatesh Rao\u2019s charge is that AI debate races past the ontological questions straight to moral verdicts - he calls it premature ontological closure. His counter-frame is cellular: humans as mitochondria supplying what he calls liveness (attention, desire, stakes, embodied judgment) while AI occupies the nuclear position of the emerging cell. A Copernican de-centering, offered as a pre-moral framing device - meant to be argued with before it is judged.',source:{label:'Contraptions',url:'https://contraptions.venkateshrao.com/p/our-eukaryotic-moment'},tags:['Foundations','Agents']},
{date:'13 Sep 2026',title:'Augment\u2019s software factory, with receipts',body:'Augment published its own numbers for eight months of an agent-run SDLC: 4.5x size-adjusted output per developer, merge times down 72%, revert rates down 79% - vendor-published, so read them as their report, not an independent audit. The useful part is the sequencing: agents were added wherever work piled up, while humans kept product decisions, architecture and production risk.',source:{label:'Augment Code',url:'https://www.augmentcode.com/blog/beyond-ai-coding-agents-how-we-built-augments-software-factory'},tags:['Agents','Craft']},
{date:'13 Sep 2026',title:'Compose the interface, don\u2019t generate it',body:'A practitioner\u2019s distinction worth keeping: generated UI puts the model on the hook for accessibility, validation and browser quirks it cannot guarantee; composed UI lets the model choose and configure primitives while deterministic software owns how they behave. Argued from a production MCP deployment, not a demo. The genieUI card, one find down, is the same argument shipped as a product.',source:{label:'David Golverdingen',url:'https://dev.to/david_golverdingen_b133a5/dont-generate-the-ui-let-ai-compose-it-3167'},tags:['Interfaces','Agents']},
{date:'12 Sep 2026',title:'genieUI: a genie with rules',body:'genieUI lets an AI compose interfaces only from components you have registered - it selects, configures, and positions them, but never invents markup. The interesting design decision is the boundary itself: the catalog of real components is what keeps everything the model makes editable afterward. The composed-vs-generated argument behind it, written up a day later in the find above.',source:{label:'genieUI',url:'https://genieui.com/'},tags:['Interfaces','Tools']},
{date:'12 Sep 2026',title:'O\u2019Reilly: the interfaces are the story',body:'O\u2019Reilly Radar\u2019s case that the consequential AI news is coming from standards bodies, not model labs: MCP and A2A sit under neutral Linux Foundation governance, and competitors are cooperating on the interfaces between their agents. The best line is the security one - a tool\u2019s self-description can inform a trust decision, but never establish it.',source:{label:'O\u2019Reilly Radar',url:'https://www.oreilly.com/radar/the-interfaces-are-arriving/'},tags:['Agents','Interfaces']},
{date:'12 Sep 2026',title:'Turkle: drop the first person',body:'Sherry Turkle in The Atlantic: the dangerous design choice is the \u2018I\u2019. A chatbot that speaks in first person promises a companion no human can be - always available, never judgmental - and that register is what hooks kids. Her ask lands on our desk: conversational voice is a design decision with a body count, not a brand exercise.',source:{label:'The Atlantic',url:'https://www.theatlantic.com/ideas/2026/09/meta-settlement-social-media-addiction-youth/688567/'},tags:['Interfaces','Craft']},
{date:'12 Sep 2026',title:'ZURB: judgment is the budget now',body:'ZURB\u2019s Radar argues the cost of a prototype has collapsed to an afternoon, so the scarce work moved to deciding which of twenty versions ships. Their fix is to write the evaluation criteria before anything gets made - the eval is the new spec. Bonus threads: the design system as a contract with your second user, the agent.',source:{label:'ZURB Radar',url:'https://radar.zurb.com/article/prototypes-now-cost-an-afternoon-so-the-scarce-work-is-judging-which-one-ships'},tags:['Craft','Agents']},
{date:'12 Sep 2026',title:'The case against building for agents',body:'Sean Goedecke takes the other side of the dual-native argument: agents use computers the way humans do, so redesigning tools for them mostly rebuilds the same thing. Training-data familiarity is a moat no agent-specific tool clears, and nobody has measured ideal agent ergonomics. Right now, building for agents just means a good API.',source:{label:'Sean Goedecke',url:'https://www.seangoedecke.com/dont-build-tools-for-ai-agents/'},tags:['Agents','Interfaces']},
{date:'11 Sep 2026',title:'Intercom measures what users actually feel about agents',body:'Intercom surveyed 1,000+ end users: 49% report positive AI agent experiences, rising to 74% once they watch an agent resolve a real query - but 54% trust AI only for simple, routine issues. Trust is conditional on stakes, and the report\u2019s argument is that experiences can be designed to earn it rather than accruing it by exposure.',source:{label:'Intercom',url:'https://www.intercom.com/blog/the-2026-ai-sentiment-report/'},tags:['Agents','Craft']},
{date:'11 Sep 2026',title:'Sierra\u2019s interface morphs with the conversation',body:'Sierra ships multimodal agents that pick the medium per beat: voice to explain, a visual to compare, a tap to confirm - without restarting the conversation. Interactive cards, tables, and forms arrive through their MCP UI integration, hosted by the customer\u2019s team and updated once across every channel. The conversation stops being a channel and becomes the orchestrator.',source:{label:'Sierra',url:'https://sierra.ai/blog/multimodal-agents'},tags:['Interfaces','Agents']},
{date:'10 Sep 2026',title:'Smashing argues the button is dying',body:'Smashing Magazine makes the case that the point-and-click contract is ending: intent-driven design collapses the ten-click flow into one stated goal, and the designer\u2019s job shifts from drawing screens to guiding transparent agent behaviour. A mainstream design publication saying the best interface is no interface moves the idea from niche to canon.',source:{label:'Smashing Magazine',url:'https://www.smashingmagazine.com/2026/09/death-button-why-best-interface-is-no-interface/'},tags:['Interfaces','Craft']},
{date:'10 Sep 2026',title:'OUI-1 puts generative UI on consumer GPUs',body:'Thesys ships OUI-1, an open-weight DiffusionGemma finetune that writes interfaces in OpenUI Lang and scores 71.7% on the Generative UI Benchmark, 5.5x its base model. Diffusion decoding writes 256-token blocks at once, so interfaces stream in under a second on an RTX 5090. Generative UI stops needing a datacenter.',source:{label:'OpenUI (Thesys)',url:'https://www.openui.com/blog/oui-1'},tags:['Interfaces','Tools']},
{date:'10 Sep 2026',title:'WebMCP hits Chrome origin trial',body:'Pages registering their own tools for browser agents - the semantic contract stops being advice and becomes a Chrome 149 origin trial. Interface designers now ship an API whether they meant to or not.',source:{label:'Adam Arantes',url:'https://adamarant.com/en/blog/webmcp-in-2026-the-browser-api-that-lets-agents-use-your-saas-ui'},tags:['Agents','Interfaces']},
{date:'10 Sep 2026',title:'Figma opens to third-party agent workflows',body:'Figma\u2019s MCP server now lets external agents work the canvas, alongside animated shaders. The design tool becomes something agents work in, not just something humans draw in. Watch review and approval patterns follow.',source:{label:'Mike Gingerich',url:'https://www.mikegingerich.com/blog/figma-adds-animated-shaders-third-party-ai-agent-support/'},tags:['Craft','Tools']},
{date:'10 Sep 2026',title:'A2UI settles in as the generative-UI contract',body:'Google\u2019s declarative JSON protocol for agent-generated UI is the current production spec (v0.9.1). Agents describe surfaces and actions; renderers map them to real components. Generative UI gets a standard instead of a demo.',source:{label:'AI Stack Current',url:'https://aistackcurrent.com/protocols/a2ui/'},tags:['Agents','Interfaces']}];
