export type FreshFind={date:string;title:string;body:string;source:{label:string;url:string};tags:string[]};
export const freshFinds:FreshFind[]=[
{date:'11 Sep 2026',title:'Intercom measures what users actually feel about agents',body:'Intercom surveyed 1,000+ end users: 49% report positive AI agent experiences, rising to 74% once they watch an agent resolve a real query - but 54% trust AI only for simple, routine issues. Trust is conditional on stakes, and the report\u2019s argument is that experiences can be designed to earn it rather than accruing it by exposure.',source:{label:'Intercom',url:'https://www.intercom.com/blog/the-2026-ai-sentiment-report/'},tags:['Agents','Craft']},
{date:'11 Sep 2026',title:'Sierra\u2019s interface morphs with the conversation',body:'Sierra ships multimodal agents that pick the medium per beat: voice to explain, a visual to compare, a tap to confirm - without restarting the conversation. Interactive cards, tables, and forms arrive through their MCP UI integration, hosted by the customer\u2019s team and updated once across every channel. The conversation stops being a channel and becomes the orchestrator.',source:{label:'Sierra',url:'https://sierra.ai/blog/multimodal-agents'},tags:['Interfaces','Agents']},
{date:'10 Sep 2026',title:'Smashing argues the button is dying',body:'Smashing Magazine makes the case that the point-and-click contract is ending: intent-driven design collapses the ten-click flow into one stated goal, and the designer\u2019s job shifts from drawing screens to guiding transparent agent behaviour. A mainstream design publication saying the best interface is no interface moves the idea from niche to canon.',source:{label:'Smashing Magazine',url:'https://www.smashingmagazine.com/2026/09/death-button-why-best-interface-is-no-interface/'},tags:['Interfaces','Craft']},
{date:'10 Sep 2026',title:'OUI-1 puts generative UI on consumer GPUs',body:'Thesys ships OUI-1, an open-weight DiffusionGemma finetune that writes interfaces in OpenUI Lang and scores 71.7% on the Generative UI Benchmark, 5.5x its base model. Diffusion decoding writes 256-token blocks at once, so interfaces stream in under a second on an RTX 5090. Generative UI stops needing a datacenter.',source:{label:'OpenUI (Thesys)',url:'https://www.openui.com/blog/oui-1'},tags:['Interfaces','Tools']},
{date:'10 Sep 2026',title:'WebMCP hits Chrome origin trial',body:'Pages registering their own tools for browser agents - the semantic contract stops being advice and becomes a Chrome 149 origin trial. Interface designers now ship an API whether they meant to or not.',source:{label:'Adam Arantes',url:'https://adamarant.com/en/blog/webmcp-in-2026-the-browser-api-that-lets-agents-use-your-saas-ui'},tags:['Agents','Interfaces']},
{date:'10 Sep 2026',title:'Figma opens to third-party agent workflows',body:'Figma\u2019s MCP server now lets external agents work the canvas, alongside animated shaders. The design tool becomes something agents work in, not just something humans draw in. Watch review and approval patterns follow.',source:{label:'Mike Gingerich',url:'https://www.mikegingerich.com/blog/figma-adds-animated-shaders-third-party-ai-agent-support/'},tags:['Craft','Tools']},
{date:'10 Sep 2026',title:'A2UI settles in as the generative-UI contract',body:'Google\u2019s declarative JSON protocol for agent-generated UI is the current production spec (v0.9.1). Agents describe surfaces and actions; renderers map them to real components. Generative UI gets a standard instead of a demo.',source:{label:'AI Stack Current',url:'https://aistackcurrent.com/protocols/a2ui/'},tags:['Agents','Interfaces']}];
