'use client';
import Link from 'next/link';import {useEffect,useMemo,useState} from 'react';import {cases} from './data';import {resources} from './resourceData';import {freshFinds} from './freshData';import {tools} from './toolsData';import {sourceTracks} from './sourcesData';import {territories} from './atlasData';import {snapshots} from './benchData';
import ThemeToggle from './ThemeToggle';
import {Badge} from '@astryxdesign/core/Badge';
import XRightRail from './XRightRail';
type Row={group:string;tag:string;sender:string;title:string;preview:string;href:string;time:string;accent?:string;keywords?:string};
const patternCount=resources.reduce((n,r)=>n+(r.access==='Hosted'?r.components.length:1),0),readingCount=sourceTracks.reduce((n,t)=>n+t.items.length,0);
const systemRows:Row[]=[
{group:'System',tag:'START',sender:'Open design system',title:'Learn the field. Try the patterns. Ship the decisions.',preview:'The organised map for everything AI-native design in this portfolio.',href:'/system',time:'Start',accent:'blue'},
{group:'System',tag:'TRY',sender:'Pattern wall',title:`${patternCount} live interface patterns`,preview:'Working behaviours with source, access and licence attached.',href:'/resources',time:'Live',accent:'green'},
{group:'System',tag:'BUILD',sender:'Component catalogue',title:'Twelve AI-native component jobs',preview:'States to design, examples to inspect and a six-step build guide.',href:'/components',time:'Guide',accent:'violet'},
{group:'System',tag:'SPEC',sender:'Open starter kit',title:'Seventeen project templates',preview:'Behaviour, grounding, evaluation, failure, approval and handoff.',href:'/library',time:'Copy',accent:'orange'},
{group:'Learn',tag:'APPLY',sender:'Process manual',title:'Brief to shipped in ten steps',preview:'Tools, templates, failure modes and the test for moving on.',href:'/process',time:'10 steps',keywords:'design process ai native workflow method manual'},
{group:'Learn',tag:'READ',sender:'Sources',title:`${readingCount} readings in sequence`,preview:'Foundations, interfaces, agents and craft, each with a note.',href:'/sources',time:'Read'},
{group:'Learn',tag:'MAP',sender:'Atlas',title:`${territories.length} territories across the field`,preview:'Patterns, templates and case evidence connected by one taxonomy.',href:'/atlas',time:'Map'},
{group:'Live',tag:'SCORES',sender:'Benchmarks',title:`${snapshots[0].rows[0].model} leads the tracked board`,preview:'Every category and cut, mirrored from the live board and refreshed hourly.',href:'/benchmarks',time:'Hourly',accent:'gold'},
{group:'Live',tag:'TOOLS',sender:'Tool watch',title:`${tools.length} tools that earned a place`,preview:'Agent-ready systems, generative UI and design workflow tools.',href:'/tools',time:'Current'},
{group:'Learn',tag:'ESSAY',sender:'Thinking',title:'The judgment behind the system',preview:'Working principles, decisions and what is not delegated.',href:'/thinking',time:'Notes'},
{group:'System',tag:'PROOF',sender:'Evidence map',title:'Claims mapped to their proof',preview:'What is strong, partial or still needs evidence.',href:'/capabilities',time:'Check'},
{group:'System',tag:'RULES',sender:'Accessibility',title:'Keyboard, motion and responsive rules',preview:'The inclusion contract for the live system.',href:'/accessibility',time:'Rules'}];
const caseRows:Row[]=cases.map((c,i)=>({group:'Cases',tag:c.category[0].toUpperCase(),sender:'Case study',title:c.title,preview:c.summary,href:`/work/${c.slug}`,time:String(i+1).padStart(2,'0'),accent:c.accent,keywords:c.category.join(' ')}));
const newsRows:Row[]=freshFinds.map((f,i)=>({group:'News',tag:'NEW',sender:f.source.label,title:f.title,preview:f.body,href:'/fresh',time:f.date,accent:'red',keywords:`ai native design news ${f.tags.join(' ')}`}));
const primaryRows=[...systemRows];
const searchableRows=[...systemRows,...caseRows,...newsRows];
const nav=[['Home','All'],['AI-native news','News'],['Open design system','System'],['Case studies','Cases'],['Learn AI-native design','Learn'],['Live field','Live']];
const labels=[['System map','/system'],['Patterns','/resources'],['Components','/components'],['Templates','/library'],['Process','/process'],['Sources','/sources'],['Atlas','/atlas'],['Benchmarks','/benchmarks'],['Tools','/tools'],['Fresh','/fresh']];
export default function InboxHome(){const [group,setGroup]=useState('All'),[q,setQ]=useState(''),[focused,setFocused]=useState(false);useEffect(()=>{const sync=()=>{if(location.hash==='#cases')setGroup('Cases')};sync();addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);const terms=q.toLowerCase().trim().split(/\s+/).filter(Boolean);const matches=(r:Row)=>{const hay=`${r.sender} ${r.title} ${r.preview} ${r.tag} ${r.group} ${r.keywords||''}`.toLowerCase();return terms.every(term=>hay.includes(term))};const folderRows=group==='All'?primaryRows:searchableRows.filter(r=>r.group===group);const rows=useMemo(()=>q.trim()?searchableRows.filter(r=>(group==='All'||r.group===group)&&matches(r)):folderRows,[group,q]);const suggestions=useMemo(()=>q.trim()?searchableRows.filter(r=>(group==='All'||r.group===group)&&matches(r)).slice(0,6):[],[group,q]);return <main className="inbox-page">
<header className="inbox-top"><button className="inbox-menu" aria-label="Open navigation">☰</button><Link href="/" className="inbox-brand"><i>𝕏</i><span>Ayodhya</span><b>AI-native design</b></Link><div className="inbox-search-wrap"><label className="inbox-search"><span>⌕</span><input value={q} onFocus={()=>setFocused(true)} onBlur={()=>setTimeout(()=>setFocused(false),120)} onChange={e=>setQ(e.target.value)} placeholder="Search Ayodhya’s work" aria-label="Search Ayodhya’s work" autoComplete="off"/></label>{focused&&q.trim()&&<div className="search-suggest" role="listbox">{suggestions.length?suggestions.map(r=><Link href={r.href} key={`${r.group}-${r.title}`}><i>{r.group}</i><span><b>{r.title}</b><small>{r.preview}</small></span></Link>):<p>No matching design-system mail</p>}</div>}</div><nav><Link href="/contact">Contact</Link><a href="https://github.com/ayodhyamohanthy/ai-portfolio">GitHub ↗</a><ThemeToggle/><i>AM</i></nav></header>
<div className="inbox-layout"><aside className="inbox-side"><Link className="compose" href="/contact"><b>Message</b></Link><div className="mail-folders">{nav.map(([label,value])=><button key={value} onClick={()=>setGroup(value)} aria-pressed={group===value}><span>{value==='All'?'▣':value==='Cases'?'◆':value==='Live'?'◉':'▤'}</span>{label}<b>{value==='All'?primaryRows.length:value==='News'?newsRows.length:value==='Cases'?caseRows.length:value==='System'?systemRows.filter(x=>x.group==='System').length:value==='Learn'?systemRows.filter(x=>x.group==='Learn').length:systemRows.filter(x=>x.group==='Live').length}</b></button>)}</div><p>LABELS</p><div className="mail-labels">{labels.map(([label,href])=><Link key={href} href={href}><i/> {label}</Link>)}</div><footer><Link href="/system">About this system</Link><Link href="/resources/credits">Credits + licences</Link><Link href="/accessibility">Accessibility</Link></footer></aside>
<section className="inbox-main"><div className="inbox-toolbar"><div><button aria-label="Select all">□</button><button aria-label="Refresh">↻</button><button aria-label="More">⋮</button></div><span>{rows.length} items</span></div><div className="inbox-tabs">{[['All','For you'],['News','AI-native news'],['Cases','Case studies'],['System','Open system'],['Live','Benchmarks']].map(([value,label])=><button key={value} onClick={()=>setGroup(value)} aria-pressed={group===value}><i>{value==='All'?'▣':value==='Cases'?'◆':value==='Live'?'◉':'▤'}</i><span>{label}<small>{value==='All'?'Everything AI-native':value==='Cases'?'Shipped product work':value==='System'?'Patterns + rules':'Current field signal'}</small></span></button>)}</div><div className="inbox-context"><div><b>{group==='All'?'Primary · open design system':group==='News'?'AI-native design news':group}</b><span>{group==='All'?'System, learning and live-field mail only. Case studies and news stay in their own folders.':group==='News'?'Newest verified field changes arrive first, like unread mail.':group==='Cases'?'Design work, evidence and outcomes.':group==='System'?'The reusable system: map, patterns, components, templates and rules.':group==='Learn'?'Read, map, apply and form your own judgment.':'Benchmarks, tools and verified new field notes.'}</span></div><Link href="/system">Open system map →</Link></div><div className="mail-list">{rows.map((r,i)=><Link href={r.href} className={`mail-row ${i<4?'unread':''}`} key={`${r.group}-${r.href}`}><span className="mail-check">□</span><span className="mail-star">☆</span><b className="mail-sender">{r.sender}</b><Badge className={`mail-tag ${r.accent||''}`} label={r.tag}/><span className="mail-copy"><b>{r.title}</b><i> - {r.preview}</i></span><time>{r.time}</time></Link>)}</div><div className="inbox-empty">You reached the end of the system. <Link href="/system">Return to the map →</Link></div></section><XRightRail/></div>
<nav className="inbox-mobile-nav">{[['All','Home','⌂'],['News','News','●'],['System','System','▤'],['Cases','Cases','◆'],['Live','Live','◉']].map(([value,label,icon])=><button onClick={()=>setGroup(value)} aria-pressed={group===value} key={value}><i>{icon}</i><span>{label}</span></button>)}</nav></main>}
