'use client';
import Link from 'next/link';import {useEffect,useMemo,useState} from 'react';import {cases} from './data';import {resources} from './resourceData';import {freshFinds} from './freshData';import {tools} from './toolsData';import {sourceTracks} from './sourcesData';import {territories} from './atlasData';import {snapshots} from './benchData';
import {Badge} from '@astryxdesign/core/Badge';
import Icon from './Icons';
type Row={group:string;tag:string;sender:string;title:string;preview:string;href:string;time:string;accent?:string;keywords?:string};
const patternCount=resources.reduce((n,r)=>n+(r.access==='Hosted'?r.components.length:1),0),readingCount=sourceTracks.reduce((n,t)=>n+t.items.length,0);
const systemRows:Row[]=[
{group:'System',tag:'START',sender:'Open design system',title:'Learn the field. Try the patterns. Ship the decisions.',preview:'The organised map for everything AI-native design in this portfolio.',href:'/system',time:'Start',accent:'blue'},
{group:'System',tag:'TRY',sender:'Pattern wall',title:`${patternCount} live interface patterns`,preview:'Working behaviours with source, access and licence attached.',href:'/resources',time:'Live',accent:'green'},
{group:'System',tag:'BUILD',sender:'Component catalogue',title:'Twelve AI-native component jobs',preview:'States to design, examples to inspect and a six-step build guide.',href:'/components',time:'Guide',accent:'violet'},
{group:'System',tag:'SPEC',sender:'Open starter kit',title:'Seventeen project templates',preview:'Behaviour, grounding, evaluation, failure, approval and handoff.',href:'/library',time:'Copy',accent:'orange'},
{group:'Learn',tag:'APPLY',sender:'Process manual',title:'Brief to shipped in ten steps',preview:'Tools, templates, failure modes and the test for moving on.',href:'/process',time:'10 steps',keywords:'design process ai native workflow method manual'},
{group:'Learn',tag:'READ',sender:'Sources',title:`${readingCount} readings in sequence`,preview:'Foundations, interfaces, agents and craft, each with a note.',href:'/sources',time:'Read'},
{group:'Learn',tag:'MAP',sender:'Atlas',title:`${territories.length} territories across the field`,preview:'Patterns, templates and case evidence connected by one taxonomy.',href:'/atlas',time:'Map'},
{group:'Benchmarks',tag:'SCORES',sender:'Benchmarks',title:`${snapshots[0].rows[0].model} leads the tracked board`,preview:'Every category and cut, mirrored from the live board and refreshed hourly.',href:'/benchmarks',time:'Hourly',accent:'gold'},
{group:'Tools',tag:'TOOLS',sender:'Tool watch',title:`${tools.length} tools that earned a place`,preview:'Agent-ready systems, generative UI and design workflow tools.',href:'/tools',time:'Current'},
{group:'Primary',tag:'ESSAY',sender:'Thinking',title:'The judgment behind the system',preview:'Working principles, decisions and what is not delegated.',href:'/thinking',time:'Notes'},
{group:'Primary',tag:'PROOF',sender:'Evidence map',title:'Claims mapped to their proof',preview:'What is strong, partial or still needs evidence.',href:'/capabilities',time:'Check'},
{group:'Primary',tag:'RULES',sender:'Accessibility',title:'Keyboard, motion and responsive rules',preview:'The inclusion contract for the live system.',href:'/accessibility',time:'Rules'}];
const casePriority=['application-automation','clinical-trial-tool','data-product-design','ai-interface-exploration','healthcare-pilot','ad-platform','telemetry','orbit','skipwait','tat-realtime'];
const caseRows:Row[]=casePriority.map(slug=>cases.find(c=>c.slug===slug)!).map((c,i)=>({group:'Cases',tag:c.category[0].toUpperCase(),sender:'Case study',title:c.title,preview:c.summary,href:`/work/${c.slug}`,time:String(i+1).padStart(2,'0'),accent:c.accent,keywords:c.category.join(' ')}));
const newsRows:Row[]=freshFinds.map((f,i)=>({group:'News',tag:'NEW',sender:f.source.label,title:f.title,preview:f.body,href:'/fresh',time:f.date,accent:'red',keywords:`ai native design news ${f.tags.join(' ')}`}));
const primaryRows:Row[]=[{group:'Primary',tag:'HELLO',sender:'Ayodhya Mohanthy',title:'Head of AI-Native Product Design',preview:'Shipped work, system thinking and the judgment to lead both.',href:'/contact',time:'Start',accent:'blue'},...systemRows.filter(r=>r.group==='Primary')];
const searchableRows=[...systemRows,...caseRows,...newsRows];
const nav=[['Primary','All'],['Case studies','Cases'],['Open design system','System'],['Learn AI-native design','Learn'],['AI-native news','News'],['Benchmarks','Benchmarks']];
const tabs=[['All','Primary'],['Cases','Case studies'],['System','Open system'],['Learn','Learn'],['News','AI-native news'],['Benchmarks','Benchmarks']];
export default function InboxHome(){const [group,setGroupState]=useState('All'),[q,setQ]=useState(''),[focused,setFocused]=useState(false);const setGroup=(next:string)=>{setGroupState(next);setQ('');const view=next==='All'?'':next.toLowerCase();history.replaceState(null,'',view?`/?view=${view}`:'/')};useEffect(()=>{const sync=()=>{const view=new URLSearchParams(location.search).get('view');const next=location.hash==='#cases'?'Cases':view==='cases'?'Cases':view==='news'?'News':view==='system'?'System':view==='learn'?'Learn':view==='benchmarks'?'Benchmarks':'All';setGroupState(next)};sync();addEventListener('hashchange',sync);addEventListener('popstate',sync);return()=>{removeEventListener('hashchange',sync);removeEventListener('popstate',sync)}},[]);const terms=q.toLowerCase().trim().split(/\s+/).filter(Boolean);const matches=(r:Row)=>{const hay=`${r.sender} ${r.title} ${r.preview} ${r.tag} ${r.group} ${r.keywords||''}`.toLowerCase();return terms.every(term=>hay.includes(term))};const folderRows=group==='All'?primaryRows:searchableRows.filter(r=>r.group===group);const rows=useMemo(()=>q.trim()?searchableRows.filter(r=>(group==='All'||r.group===group)&&matches(r)):folderRows,[group,q]);const suggestions=useMemo(()=>q.trim()?searchableRows.filter(r=>(group==='All'||r.group===group)&&matches(r)).slice(0,6):[],[group,q]);return <main className="inbox-page">
<header className="inbox-top"><button className="inbox-menu" aria-label="Open navigation"><Icon name="menu"/></button><Link href="/" className="inbox-brand"><i>AM</i><span>Ayodhya</span><b>AI-native design</b></Link><div className="inbox-search-wrap"><label className="inbox-search"><span><Icon name="search"/></span><input value={q} onFocus={()=>setFocused(true)} onBlur={()=>setTimeout(()=>setFocused(false),120)} onChange={e=>setQ(e.target.value)} placeholder="Search the design system" aria-label="Search the design system" autoComplete="off"/></label>{focused&&q.trim()&&<div className="search-suggest" role="listbox">{suggestions.length?suggestions.map(r=><Link href={r.href} key={`${r.group}-${r.title}`}><i>{r.group}</i><span><b>{r.title}</b><small>{r.preview}</small></span></Link>):<p>No matching design-system mail</p>}</div>}</div><nav><Link href="/contact">Contact</Link><a href="https://github.com/ayodhyamohanthy/ai-portfolio">GitHub ↗</a><i>AM</i></nav></header>
<div className="inbox-layout"><aside className="inbox-side"><Link className="compose" href="/contact"><Icon name="compose"/> <b>Drop me a message</b></Link><div className="mail-folders">{nav.map(([label,value])=><button key={value} onClick={()=>setGroup(value)} aria-pressed={group===value}><span><Icon name={value==='All'?'inbox':value==='News'?'news':value==='Cases'?'case':value==='Learn'?'learn':value==='Benchmarks'?'live':'system'}/></span>{label}<b>{value==='All'?primaryRows.length:value==='News'?newsRows.length:value==='Cases'?caseRows.length:value==='System'?systemRows.filter(x=>x.group==='System').length:value==='Learn'?systemRows.filter(x=>x.group==='Learn').length:systemRows.filter(x=>x.group==='Benchmarks').length}</b></button>)}</div><p>ORDERED FOR REVIEW</p><div className="folder-rule">Leadership → work → system → learning → news → live data</div><footer><Link href="/system">About this system</Link><Link href="/resources/credits">Credits + licences</Link><Link href="/accessibility">Accessibility</Link></footer></aside>
<section className="inbox-main"><div className="inbox-toolbar"><div><button aria-label="Select all"><Icon name="check"/></button><button aria-label="Refresh"><Icon name="refresh"/></button><button aria-label="More"><Icon name="more"/></button></div><span>{rows.length} items</span></div><div className="inbox-tabs">{tabs.map(([value,label])=><button key={value} onClick={()=>setGroup(value)} aria-pressed={group===value}><i><Icon name={value==='All'?'inbox':value==='News'?'news':value==='Cases'?'case':value==='Learn'?'learn':value==='Benchmarks'?'live':'system'}/></i><span>{label}<small>{value==='All'?'Leadership first':value==='Cases'?'Strongest evidence first':value==='System'?'Map to templates':value==='Learn'?'Process to sources':value==='News'?'Newest first':'Live data only'}</small></span></button>)}</div><div className="inbox-context"><div><b>{group==='All'?'Primary · leadership profile':group==='News'?'AI-native design news':group}</b><span>{group==='All'?'Start here: leadership position, judgment, evidence and accessibility.':group==='News'?'Newest verified field changes arrive first, like unread mail.':group==='Cases'?'Design work, evidence and outcomes.':group==='System'?'The reusable system: map, patterns, components, templates and rules.':group==='Learn'?'Process, sources and the field atlas.':'The hourly Design Arena model boards, and nothing else.'}</span></div><Link href="/system">Open system map →</Link></div><div className="mail-list">{rows.map((r,i)=><Link href={r.href} className={`mail-row ${i<4?'unread':''}`} key={`${r.group}-${r.href}`}><span className="mail-check"><Icon name="check" size={17}/></span><span className="mail-star"><Icon name="star" size={17}/></span><b className="mail-sender">{r.sender}</b><Badge className={`mail-tag ${r.accent||''}`} label={r.tag}/><span className="mail-copy"><b>{r.title}</b><i> - {r.preview}</i></span><time>{r.time}</time></Link>)}</div><div className="inbox-empty">You reached the end of the system. <Link href="/system">Return to the map →</Link></div></section></div>
<nav className="inbox-mobile-nav">{[['All','Primary','▣'],['Cases','Cases','◆'],['System','System','▤'],['Learn','Learn','◈'],['News','News','●'],['Benchmarks','Boards','◉']].map(([value,label,icon])=><button onClick={()=>setGroup(value)} aria-pressed={group===value} key={value}><i><Icon name={value==='All'?'inbox':value==='News'?'news':value==='Cases'?'case':value==='Benchmarks'?'live':'system'}/></i><span>{label}</span></button>)}</nav></main>}
