export type ProcTool={name:string,url:string,what:string,pick:string};
export type ProcTemplate={label:string,text:string};
export type ProcStep={n:string,name:string,claim:string,body:string,tools:ProcTool[],templates:ProcTemplate[],failures:string[],good:string,doneWhen:string};
export const steps:ProcStep[]=[
{n:'01',name:'Brief',claim:'Decide what done looks like.',body:'Everything downstream inherits the brief. A vague brief gives you vague screens, faster - and AI will happily design the wrong product beautifully. The brief is the one artifact that is entirely yours, and it is short: who it is for, what they are trying to do, when it fails today, what done looks like. Do not open a design tool until it exists.',tools:[
{name:'Claude',url:'https://claude.ai',what:'Paste your idea. Ask it to interview you, one question at a time, until the brief is sharp.',pick:'The default interviewer. Strong at pushing back on vague answers.'},
{name:'Gemini',url:'https://gemini.google.com',what:'Google\u2019s chat model - same interview play, different voice.',pick:'When you live in Google\u2019s stack, or want a second interviewer to catch what the first missed.'}],templates:[{label:'PROMPT TEMPLATE · THE INTERVIEW',text:'I want to design [the thing]. Interview me one question at a time until you can write a one-paragraph brief that names: who it is for, what they are trying to do, when it fails them today, and what "done" looks like. Then write the brief.'},{label:'TEMPLATE · THE BRIEF ITSELF',text:'For [who - one kind of person, not "users"].\nThey are trying to [the job, in their words].\nToday it fails when [the specific moment it breaks].\nDone looks like [an outcome a stranger could verify].\nNot in scope: [what you are NOT designing - one line that saves you later].'}],failures:['Writing the brief as a feature list. Features are answers; the brief is the question.','Skipping the not-in-scope line. Scope creep starts here, not in the build.','Letting the AI write the brief without the interview. It fills your gaps with averages.'],good:'What good looks like: a stranger reads it and describes the same product back to you.',doneWhen:'You can read the brief to a stranger and they can describe the product back to you.'},
{n:'02',name:'Eval',claim:'Write the test before the answer.',body:'ZURB\u2019s line, and the best idea in design right now: the eval is the new spec. When a prototype costs an afternoon, the scarce work is judging which one ships. Write the criteria now, while you are still impartial - after you see directions, you will write criteria that fit your favorite. Three to five criteria, each one observable, each one scored 0 or 1.',tools:[
{name:'Claude',url:'https://claude.ai',what:'Same thread. Turn the brief into pass/fail criteria you could hold a screen against.',pick:'For drafting the criteria - you still own every word.'},
{name:'ZURB Radar',url:'https://radar.zurb.com/article/prototypes-now-cost-an-afternoon-so-the-scarce-work-is-judging-which-one-ships',what:'The reading this step is built on.',pick:'Ten minutes that will change how you judge everything after.'}],templates:[{label:'EVAL TEMPLATE · THE SPEC',text:'A direction passes when:\n1. A first-time user can [core job from the brief] in under [N] steps.\n2. The first screen answers "what is this, and is it for me" in 5 seconds.\n3. [One criterion of your own - make it observable.]\nScore every direction 0 or 1 per criterion. Below full marks: iterate, don\u2019t ship.'},{label:'TEMPLATE · THE SCORECARD',text:'Scorecard - one row per direction, one column per criterion.\nDirection | C1 | C2 | C3 | Verdict\nA         |    |    |    |\nB         |    |    |    |\nC         |    |    |    |\nRule: the verdict is written from the scores, not from memory of which one looked nicest.'}],failures:['Criteria you cannot observe. "Feels premium" is not a criterion; "loads in under 3 seconds on a phone" is.','Writing evals after seeing the directions. That is rationalizing, not evaluating.','More than five criteria. Past five, none of them bite.'],good:'What good looks like: two people score the same screen the same way without talking.',doneWhen:'The criteria are specific enough that two people would score the same screen the same way.'},
{n:'03',name:'Research',claim:'Collect proof before you invent.',body:'This is not academic research. You are loading two contexts with real decisions: yours, and the machine\u2019s. Two kinds of proof matter - what users actually do (evidence) and what real products already do (references). An hour here saves days of generating plausible nonsense.',tools:[
{name:'Mobbin',url:'https://mobbin.com',what:'Real screens from real apps, searchable by flow and pattern.',pick:'When you need to see how proven products solved your exact flow.'},
{name:'Claude',url:'https://claude.ai',what:'Summarize a landscape, list competitors, draft research questions.',pick:'For breadth - then open the sources it names. An unverified summary is a rumor.'},
{name:'User Interviews',url:'https://www.userinterviews.com',what:'Recruit real people matching your audience for research sessions.',pick:'When the question needs a human, not a summary - recruit the actual users.'},
{name:'The Atlas',url:'/atlas',what:'This site\u2019s map of AI-native interaction territory.',pick:'When the problem itself is AI-shaped - agent state, grounding, handoff.'}],templates:[{label:'TEMPLATE · REFERENCE LOG',text:'Reference: [app + screen]\nProblem it solves: [one line]\nWhat I am taking: [the decision, not the pixels]\nWhat I am leaving: [what does not fit my brief]'},{label:'TEMPLATE · RESEARCH QUESTIONS',text:'Three questions this design must answer:\n1. [question] - what I believe: [guess] - how I will check: [source or test]\n2. [question] - what I believe: [guess] - how I will check: [source or test]\n3. [question] - what I believe: [guess] - how I will check: [source or test]'}],failures:['Trusting AI summaries without opening the sources. Fluency is not evidence.','Collecting forty references and reading none. Ten studied beats forty saved.','Copying patterns from products with different users and different stakes.'],good:'What good looks like: every reference has one line on the decision you are taking from it.',doneWhen:'Five to ten annotated references, and your three beliefs with a way to check each.'},
{n:'04',name:'Structure',claim:'Name things before you draw them.',body:'Information architecture: what exists, what it is called, and how it connects. AI generates screens happily with no structure at all - you get beautiful orphans. Decide the objects, the navigation, and the names first. Names matter twice now: users read them, and the agents you prompt inherit them.',tools:[
{name:'Claude',url:'https://claude.ai',what:'Draft the sitemap from your brief: screens, states, jobs, links.',pick:'For the first pass - then argue with it until the map is yours.'},
{name:'Relume',url:'https://www.relume.io',what:'AI sitemap and wireframe sections, strong for marketing sites.',pick:'When the product is a website - it turns a brief into a sitemap in minutes.'},
{name:'Octopus.do',url:'https://octopus.do',what:'Visual sitemap builder - drag the structure around until it holds.',pick:'When you think better by moving boxes than by reading outlines.'}],templates:[{label:'PROMPT TEMPLATE · THE SITEMAP',text:'Here is my brief: [paste it]. List every screen and state this product needs. For each: its name, its one job, and what it links to. Flag anything the brief does not cover. Keep it under [N] screens - cut before you add.'},{label:'CHECKLIST · THE NAMING TEST',text:'- Every name is a word the user already uses, not a word from your org chart\n- Top level has 7 or fewer things\n- Every screen has exactly one job\n- You can draw the whole product on one sticky note'}],failures:['Designing screens before listing them. The list is the design.','Naming from your org chart instead of the user\u2019s vocabulary.','Eleven top-level sections. If everything is important, nothing is.'],good:'What good looks like: the whole product fits on one sticky note and a stranger can navigate it.',doneWhen:'A one-page sitemap where every screen has one job and a user-word name.'},
{n:'05',name:'Directions',claim:'Generate five, not one.',body:'Volume is the point. The same prompt into three tools gives you three schools of thought, and the differences teach you what you actually want. Keep the prompt identical across tools - you are comparing directions, not tools. Work screen by screen: asking for the whole app at once gets you an average of everything. This is the whole prompt-to-UI landscape - pick three, not eight.',tools:[
{name:'v0',url:'https://v0.dev',what:'Prompt to working UI in React, by Vercel. Code you keep.',pick:'When the direction should already be real, inspectable code.'},
{name:'Stitch',url:'https://stitch.withgoogle.com',what:'Google\u2019s prompt-to-UI design tool.',pick:'When you want fast visual directions to react to.'},
{name:'MagicPath',url:'https://www.magicpath.ai',what:'AI design on an infinite canvas.',pick:'When you want variations side by side and want to mix pieces.'},
{name:'Lovable',url:'https://lovable.dev',what:'Prompt to a running app, not just screens.',pick:'When the direction needs to work - data, states, flows - to be judged.'},
{name:'Polymet',url:'https://www.polymet.ai',what:'AI product designer that learns your existing product\u2019s patterns.',pick:'When you are generating inside an existing product, not from zero.'},
{name:'Onlook',url:'https://onlook.com',what:'Open-source visual editor for running React apps - "Cursor for designers".',pick:'When you already have code and want to design on it directly.'},
{name:'Bolt',url:'https://bolt.new',what:'Prompt to full-stack app in the browser, by StackBlitz.',pick:'When the direction needs a backend on day one - auth, database, the lot.'},
{name:'Replit',url:'https://replit.com',what:'AI app and website builder with hosting built in.',pick:'When you want idea-to-hosted in one place and never want to touch infra.'}],templates:[{label:'PROMPT TEMPLATE · GENERATION',text:'[Paste the brief from step 1]\n[Paste the eval criteria from step 2]\nGenerate one direction for the first screen. Prioritize criterion 1 over polish. No lorem ipsum - write the real microcopy. Show me the state the screen is in when it is doing its job, not an empty state.'},{label:'TEMPLATE · COMPARISON GRID',text:'One line per direction, written BEFORE scoring:\nA: [what this direction believes about the user]\nB: [same]\nC: [same]\nThen the scorecard from step 2 decides. If two tie, the one that is easier to explain wins.'}],failures:['Falling for the first good-looking output. Pretty is not passing.','Tool tourism - eight builders, eight different prompts, nothing comparable. Pick three, same prompt.','Asking for the whole app in one prompt. Screen by screen, always.'],good:'What good looks like: five directions different enough that scoring them teaches you something.',doneWhen:'Five or more directions you could defend or kill with the eval from step 2.'},
{n:'06',name:'Visual design',claim:'Pick one. Make it yours.',body:'Score the directions, pick the winner, and steal the best idea from each loser into it. Then refine - this is where taste enters, and the step you do not delegate. Type scale, spacing rule, color with a reason, assets that belong to this product. AI is excellent at variations and mediocre at restraint; restraint is your job.',tools:[
{name:'Figma',url:'https://www.figma.com',what:'Rebuild the winner properly: real type scale, real spacing, real components.',pick:'When you need full control, or a portfolio-grade artifact.'},
{name:'Figma Make',url:'https://www.figma.com/make/',what:'Keep iterating with AI inside Figma.',pick:'When you want AI speed without leaving the canvas.'},
{name:'Midjourney',url:'https://www.midjourney.com',what:'Image generation with the strongest taste in the category.',pick:'For hero imagery and texture - direct it hard or it directs you.'},
{name:'Ideogram',url:'https://ideogram.ai',what:'AI image generation, strong on rendered text.',pick:'When the asset needs real words inside it - posters, covers, type-forward graphics.'},
{name:'Recraft',url:'https://www.recraft.ai',what:'AI design generation built for brand-consistent assets and vectors.',pick:'When the assets must share one style across the whole product.'},
{name:'Lucide',url:'https://lucide.dev',what:'Open-source icon set - one consistent family, free.',pick:'The default icon answer. One family, everywhere, no exceptions.'},
{name:'Google Fonts',url:'https://fonts.google.com',what:'The free type library every stack can serve.',pick:'When you need a safe, fast, free typeface today.'},
{name:'Fontshare',url:'https://www.fontshare.com',what:'Quality free fonts with more character than the defaults.',pick:'When Google Fonts feels like wearing the same shirt as everyone.'},
{name:'Coolors',url:'https://coolors.co',what:'Fast palette generation and tuning.',pick:'When you need a palette to react to in the next five minutes.'},
{name:'Realtime Colors',url:'https://www.realtimecolors.com',what:'Preview your palette and type on a real layout, live.',pick:'Before committing - see the colors doing their actual jobs.'},
{name:'Tokens Studio',url:'https://tokens.studio',what:'Design tokens managed with Figma - one source for type, spacing, color.',pick:'When the product will grow and the tokens need to survive handoff.'},
{name:'Jitter',url:'https://jitter.video',what:'Motion design in the browser - animate the interface, export it.',pick:'When a transition sells the idea better than a static screen.'},
{name:'Rive',url:'https://rive.app',what:'Interactive animations that ship as running code, not video.',pick:'When the motion must respond to the user, not just play.'}],templates:[{label:'PROMPT TEMPLATE · REFINEMENT',text:'Keep the layout. Fix exactly these things: [specific, numbered list]. The type scale is [your scale]. Spacing follows [your rule]. Do not redesign - show me the before and after of each fix.'},{label:'TEMPLATE · THE TOKENS',text:'Type: [3 sizes max - display, body, caption] in [one typeface]\nSpacing: [one base unit - every gap is a multiple of it]\nColor: [one ink, one paper, one accent - accent means one thing]\nIcons: [one family - name it]\nRule: if an element needs a new token, the element is probably wrong.'},{label:'PROMPT TEMPLATE · ASSET GENERATION',text:'Generate an image for [exact slot in the design]. Style: [three adjectives that match the brief]. Palette: [your tokens]. It must read at [size]. No generic stock-photo people, no gradients I did not ask for. Give me four variants - I will art-direct from there.'}],failures:['Letting the tool redesign when you asked for a fix. Name the fix; keep the layout.','AI imagery that could belong to any product. If the asset has no reason, the answer is no asset.','Mixing icon families and font voices. One family each - mixing reads as accident.'],good:'What good looks like: every element traces to the brief or the eval, and nothing is decoration.',doneWhen:'Every element on the screen traces to the brief or the eval. Anything that cannot is deleted.'},
{n:'07',name:'Prototype',claim:'Make it run.',body:'A prototype that runs beats a picture of one. Real data, real states, real transitions - this is where AI-native compresses weeks into an afternoon. Stay where the direction already runs, or hand the refined design to a coding agent. Either way: match the design exactly before improving anything, and make the handoff explicit - handoff is where design quality goes to die.',tools:[
{name:'Cursor',url:'https://cursor.com',what:'AI coding agent. Give it the refined design as context.',pick:'When you want the code to be yours, in your stack, under your control.'},
{name:'Lovable',url:'https://lovable.dev',what:'Keep building where the direction already runs.',pick:'Fastest path when your winning direction came from here.'},
{name:'v0',url:'https://v0.dev',what:'Also a build target - its output is already working React.',pick:'When the direction came from v0 and you want code you can deploy.'},
{name:'Bolt',url:'https://bolt.new',what:'Full-stack in the browser, from prompt.',pick:'When the prototype needs real backend behaviour to be testable.'},
{name:'Onlook',url:'https://onlook.com',what:'Edit the running app visually; the code follows.',pick:'When the design is already code and you want to refine in place.'},
{name:'Figma Dev Mode',url:'https://www.figma.com/dev-mode/',what:'The inspect view built for developers - specs straight from the canvas.',pick:'When someone else builds what you designed.'},
{name:'Zeplin',url:'https://zeplin.io',what:'Design delivery workspace - screens, specs and versions in one place.',pick:'When the handoff is a team sport and needs a paper trail.'}],templates:[{label:'PROMPT TEMPLATE · BUILD',text:'Here is the design: [link or screenshot, plus your type and spacing tokens]. Build it as [your stack]. Match the design exactly before you improve anything. When you hit a judgment call, ask me instead of deciding silently.'},{label:'CHECKLIST · FIRST RUN',text:'- The core job from the brief works end to end on your machine\n- Real data, not placeholder - even if you typed it yourself\n- Loading, empty, and error states exist and say something useful\n- It runs on your phone, not just your laptop'},{label:'CHECKLIST · HANDOFF',text:'- Tokens named the same way in design and code\n- Every interactive state specced: hover, loading, empty, error\n- The builder saw the prototype run, not just pictures of it\n- One named owner for design decisions after handoff'}],failures:['Improving the design while building. Match first, improve second - one variable at a time.','Letting the agent decide silently. Make it ask; silent decisions compound.','Demo data that flatters the design. Real mess is the test.'],good:'What good looks like: the core job works with real data while you watch, on a phone.',doneWhen:'The core job from the brief works end to end on your machine.'},
{n:'08',name:'Test',claim:'One stranger beats ten iterations.',body:'You do not need a lab. You need one person who did not make the thing, three tasks, and the discipline to stay quiet. Two tests carry most of the weight: the five-second test (what is this, is it for me) and the task test (can they do the core job unaided). Their struggle is the data - helping them erases it.',tools:[
{name:'Claude',url:'https://claude.ai',what:'Draft the test script from your brief and eval criteria.',pick:'For the script - the session itself needs a human and silence.'},
{name:'Lyssna',url:'https://www.lyssna.com',what:'Remote unmoderated testing - five-second tests, first-click, task flows.',pick:'When you need ten strangers by tonight, not one by next week.'},
{name:'Maze',url:'https://maze.co',what:'User research and testing platform - prototype tests with metrics.',pick:'When the test needs numbers for a stakeholder, not just your own notes.'},
{name:'User Interviews',url:'https://www.userinterviews.com',what:'Recruit participants who match your actual audience.',pick:'When "whoever is nearby" is the wrong user - and it usually is.'}],templates:[{label:'TEMPLATE · THE TEST SCRIPT',text:'Setup: "I am testing the product, not you. Think out loud. I cannot help."\n1. Five-second test: show the first screen for 5 seconds. Ask: what is this, and is it for you?\n2. Task test: [core job from the brief], then [second job], then [edge case]. Watch. Say nothing.\n3. Close: what would you tell a friend this does?\nWrite down every hesitation with a timestamp. Hesitations are the next brief.'}],failures:['Helping when they struggle. The struggle IS the data.','Testing on friends who already know the product. Politeness is noise.','Asking "do you like it". Watch what they do; ignore what they say they would do.'],good:'What good looks like: a stranger completes the core job unaided and describes it back correctly.',doneWhen:'One stranger used it and you have a written list of where they hesitated.'},
{n:'09',name:'Ship',claim:'A URL beats a folder.',body:'Ship the same day. A live URL changes what the work is - people can use it, share it, and break it, and every one of those teaches you. Done is not "looks right on your machine"; done is a stranger using it without you in the room. Ship means three things: it is up, it is measured, and everyone can use it - including the people your design usually forgets.',tools:[
{name:'Vercel',url:'https://vercel.com',what:'Deploy from the repo. You get a URL in minutes.',pick:'The default. Connect the repo once; every push after that ships itself.'},
{name:'Netlify',url:'https://www.netlify.com',what:'The other great push-to-deploy host.',pick:'When your stack or your team already lives there - the discipline is the same.'},
{name:'PostHog',url:'https://posthog.com',what:'Product analytics - what users actually do, not what they say.',pick:'When you need funnels, replays and events in one place.'},
{name:'Plausible',url:'https://plausible.io',what:'Simple, privacy-friendly analytics.',pick:'When you want the truth about traffic without the cookie-banner baggage.'},
{name:'Stark',url:'https://www.getstark.co',what:'Accessibility checks inside the design tools and the browser.',pick:'Before handoff and before ship - contrast, landmarks, the lot.'},
{name:'axe DevTools',url:'https://www.deque.com/axe/',what:'The standard automated accessibility engine, in your browser.',pick:'For the pre-ship audit - catches what your eyes cannot.'},
{name:'WAVE',url:'https://wave.webaim.org',what:'Visual accessibility evaluation - errors shown on the page itself.',pick:'When you want to see the problems where they live.'}],templates:[{label:'CHECKLIST · BEFORE YOU SHARE THE URL',text:'- Loads on a phone in under 3 seconds\n- One person outside the project completes the core job without help\n- Every number and claim on the page is true and checkable\n- An automated accessibility pass shows no errors on the core flow\n- Analytics answer one question: did they do the core job\n- There is a way for a user to reach you\n- The URL has been shared with someone who did not make it'}],failures:['Waiting for perfect. Perfect is a loop count, not a launch date.','Checking accessibility after launch instead of before. The checklist is cheaper than the fix.','Analytics with no question attached. Pick the one number that proves the core job.'],good:'What good looks like: the URL works for a stranger on their phone on their network - including a stranger using a screen reader.',doneWhen:'The URL is live, measured, accessible - and someone who did not make it has used it.'},
{n:'10',name:'Iterate',claim:'The loop is the discipline.',body:'The last line of your first run - where the stranger hesitated - is the first line of your next brief. That loop is the whole discipline. Change one thing per loop where you can, keep the eval criteria from step 2 in force, and let evidence, not enthusiasm, set the order.',tools:[
{name:'Claude',url:'https://claude.ai',what:'Turn raw feedback and hesitation notes into the next brief.',pick:'Same thread, new cycle. The context compounds.'},
{name:'PostHog',url:'https://posthog.com',what:'Watch what shipped users actually do - session replays tell you where they hesitate at scale.',pick:'When the loop needs evidence from a hundred users, not three.'}],templates:[{label:'TEMPLATE · THE RETRO',text:'Loop [N] retro:\nWhat they did: [observed, not interpreted]\nWhat I expected: [be honest]\nWhat changes: [one thing]\nWhat stays: [what the eval still protects]\nNext brief\u2019s first line: [the sharpest hesitation, in their words]'}],failures:['Collecting feedback you never read. Hoarded signal is zero signal.','Changing ten things at once. Then no result means anything.','Dropping the eval criteria once the thing exists. They age; refresh them, do not abandon them.'],good:'What good looks like: every loop starts from evidence and ends with one deliberate change.',doneWhen:'The second brief exists, and its first line came from a user, not from you.'}
];
