export type ProcTool={name:string,url:string,what:string};
export type ProcStep={n:string,name:string,claim:string,body:string,tools:ProcTool[],templateLabel:string,template:string,doneWhen:string};
export const steps:ProcStep[]=[
{n:'01',name:'Brief',claim:'Decide what done looks like.',body:'Everything downstream inherits the brief. A vague brief gives you vague screens, faster. Write one paragraph before you open any design tool - and let the AI interview you until the paragraph is sharp.',tools:[{name:'Claude',url:'https://claude.ai',what:'Paste your idea. Ask it to interview you, one question at a time.'}],templateLabel:'PROMPT TEMPLATE · THE INTERVIEW',template:`I want to design [the thing]. Interview me one question at a time until you can write a one-paragraph brief that names: who it is for, what they are trying to do, when it fails them today, and what "done" looks like. Then write the brief.`,doneWhen:'You can read the brief to a stranger and they can describe the product back to you.'},
{n:'02',name:'Eval',claim:'Write the test before the answer.',body:'ZURB\u2019s line, and the best idea in design right now: the eval is the new spec. When a prototype costs an afternoon, the scarce work is judging which one ships. Decide the criteria now, while you are still impartial - before you fall in love with a direction.',tools:[{name:'Claude',url:'https://claude.ai',what:'Same thread. Turn the brief into pass/fail criteria.'},{name:'ZURB Radar',url:'https://radar.zurb.com/article/prototypes-now-cost-an-afternoon-so-the-scarce-work-is-judging-which-one-ships',what:'The reading this step is built on.'}],templateLabel:'EVAL TEMPLATE · THE SPEC',template:`A direction passes when:
1. A first-time user can [core job from the brief] in under [N] steps.
2. The first screen answers "what is this, and is it for me" in 5 seconds.
3. [One criterion of your own - make it observable.]
Score every direction 0 or 1 per criterion. Below full marks: iterate, don\u2019t ship.`,doneWhen:'The criteria are specific enough that two people would score the same screen the same way.'},
{n:'03',name:'Ground',claim:'Collect proof that it can work.',body:'Do not generate from an empty head. Find real products that solved adjacent problems and study their structure. You are stealing decisions, not pixels.',tools:[{name:'Mobbin',url:'https://mobbin.com',what:'Real screens from real apps, searchable by flow.'},{name:'The Atlas',url:'/atlas',what:'This site\u2019s map of AI-native interaction territory - find the ground your problem sits on.'}],templateLabel:'REFERENCE LOG · PER SCREEN',template:`Reference: [app + screen]
Problem it solves: [one line]
What I am taking: [the decision, not the pixels]
What I am leaving: [what does not fit my brief]`,doneWhen:'Five to ten references saved, each with one line on what you are taking from it.'},
{n:'04',name:'Diverge',claim:'Generate five directions, not one.',body:'Volume is the point. The same prompt into three tools gives you three schools of thought. Keep the prompt identical across tools so the comparison stays fair - you are testing directions, not tools.',tools:[{name:'v0',url:'https://v0.dev',what:'Prompt to working UI, by Vercel.'},{name:'Stitch',url:'https://stitch.withgoogle.com',what:'Google\u2019s prompt-to-UI design tool.'},{name:'MagicPath',url:'https://www.magicpath.ai',what:'AI design on an infinite canvas - good for exploring variations side by side.'},{name:'Lovable',url:'https://lovable.dev',what:'Prompt to a running app, not just screens.'}],templateLabel:'PROMPT TEMPLATE · GENERATION',template:`[Paste the brief from step 1]
[Paste the eval criteria from step 2]
Generate one direction for the first screen. Prioritize criterion 1 over polish. No lorem ipsum - write the real microcopy. Show me the state the screen is in when it is doing its job, not an empty state.`,doneWhen:'Five or more directions you could defend or kill with the eval from step 2.'},
{n:'05',name:'Converge',claim:'Pick one. Say why.',body:'Score every direction against the eval. Pick the winner, then steal the best idea from each loser and write it into the winner. Refinement is where taste enters - this is the step you do not delegate.',tools:[{name:'Figma',url:'https://www.figma.com',what:'Rebuild the winner properly - real type scale, real spacing.'},{name:'Figma Make',url:'https://www.figma.com/make/',what:'Keep iterating with AI inside Figma.'}],templateLabel:'PROMPT TEMPLATE · REFINEMENT',template:`Keep the layout. Fix exactly these things: [specific, numbered list]. The type scale is [your scale]. Spacing follows [your rule]. Do not redesign - show me the before and after of each fix.`,doneWhen:'Every element on the screen traces to the brief or the eval. Anything that cannot is deleted.'},
{n:'06',name:'Build',claim:'Make it run.',body:'A prototype that runs beats a picture of one. Take the winning direction to working software - this is where AI-native compresses weeks into an afternoon.',tools:[{name:'Cursor',url:'https://cursor.com',what:'AI coding agent. Give it the refined design as context.'},{name:'Lovable',url:'https://lovable.dev',what:'Or stay here if your winning direction already runs.'}],templateLabel:'PROMPT TEMPLATE · BUILD',template:`Here is the design: [link or screenshot, plus your type and spacing tokens]. Build it as [your stack]. Match the design exactly before you improve anything. When you hit a judgment call, ask me instead of deciding silently.`,doneWhen:'The core job from the brief works end to end on your machine.'},
{n:'07',name:'Ship',claim:'Put it in front of a person.',body:'Ship to a URL the same day. One real user beats ten more iterations inside your head. The process is not done when it looks right - it is done when someone who did not make it can use it.',tools:[{name:'Vercel',url:'https://vercel.com',what:'Deploy from the repo. You get a URL in minutes.'}],templateLabel:'CHECKLIST · BEFORE YOU SHARE THE URL',template:`- Loads on a phone in under 3 seconds
- One person outside the project completes the core job without help
- Every number and claim on the page is true and checkable
- The URL has been shared with someone who did not make it`,doneWhen:'A stranger used it. Write down where they hesitated - that list is your next brief.'}
];
