export type Resource={name:string,source:string,author:string,url:string,license:string,licenseUrl:string,mode:'Hosted / MIT'|'Indexed / link only',reviewed:string,forWho:'Designer'|'Developer'|'Both',use:string,categories:string[],components:string[]};
export const resources:Resource[]=[
{name:'AI interface primitives',source:'Beautiful UI',author:'Shane Levine',url:'https://www.beautifului.dev/',license:'MIT',licenseUrl:'https://www.beautifului.dev/license',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Both',use:'Compact states for AI systems where progress, reasoning, tools and human control must stay legible.',categories:['Agent state','Human control','Conversation','Tools'],components:['Loading state','Thinking trace','Streaming text','Approval card','Tool chips','Task rows','Context cards','Command search','Insight cards','Selection actions']},
{name:'Animated AI agent components',source:'beUI',author:'Saurabh (starc007)',url:'https://beui.dev/components/agents',license:'MIT public source only',licenseUrl:'https://github.com/starc007/ui-components/blob/main/LICENSE',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Developer',use:'Motion-rich public React components for agent status, tool calls and interactive product surfaces.',categories:['Agent state','Tools','Motion'],components:['Agent cards','Tool results','Animated status','Public blocks']},
{name:'beUI Pro catalogue',source:'beUI Pro',author:'beUI / Saurabh',url:'https://pro.beui.dev/components',license:'Commercial / separate terms',licenseUrl:'https://pro.beui.dev/components/pricing',mode:'Indexed / link only',reviewed:'30 Aug 2026',forWho:'Developer',use:'Paid component catalogue. Useful for discovery; no code or substantial catalogue is republished here.',categories:['Agent state','Motion'],components:['Pro motion components','Pro blocks','Pro agent surfaces']},
{name:'Rare animated components',source:'Rare UI',author:'Swapnil Kalambe',url:'https://rareui.com/components',license:'MIT components; brand/site excluded',licenseUrl:'https://rareui.com/terms',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Both',use:'Distinct interaction ideas beyond standard UI libraries, with a useful small AI kit and navigation patterns.',categories:['Navigation','Motion','Feedback'],components:['Fluid Orb','Grid Reveal','Bounce sidebar','Proximity sidebar','Step player','Code block','Scroll progress']},
{name:'Public transition patterns',source:'Transitions.dev',author:'Jakub Antalik',url:'https://github.com/Jakubantalik/transitions-dev',license:'MIT repository',licenseUrl:'https://github.com/Jakubantalik/transitions-dev/blob/main/LICENSE',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Developer',use:'Public transition code for continuity and state change. Host only entries traceable to the MIT repository.',categories:['Motion','Feedback'],components:['Enter / exit','Shared layout','List transitions','State morphs']},
{name:'Transitions.dev paid catalogue',source:'Transitions.dev',author:'Jakub Antalik',url:'https://transitions.dev/',license:'Commercial; redistribution restricted',licenseUrl:'https://transitions.dev/terms.html',mode:'Indexed / link only',reviewed:'30 Aug 2026',forWho:'Both',use:'A discovery index for paid transitions. Their terms prohibit republishing the library or a substantial part as a competing kit.',categories:['Motion','Feedback'],components:['Paid transitions','Pro catalogue']},
{name:'Design-system primitives',source:'shadcn/ui',author:'shadcn',url:'https://ui.shadcn.com/docs/components',license:'MIT',licenseUrl:'https://github.com/shadcn-ui/ui/blob/main/LICENSE.md',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Both',use:'Accessible, composable foundations that teams own as source code rather than depend on as a black-box package.',categories:['Conversation','Navigation','Human control','Feedback'],components:['Accordion','Command','Dialog','Form','Navigation menu','Sheet','Table','Tabs','Toast','Tooltip']},
{name:'Ayodhya AI interface lab',source:'Ayodhya Mohanthy',author:'Ayodhya Mohanthy',url:'/work/ai-interface-exploration',license:'Portfolio source; upstream MIT notices preserved',licenseUrl:'https://github.com/ayodhyamohanthy/ai-portfolio/tree/main/app/vendor',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Both',use:'Twenty working AI-native patterns adapted to real portfolio evidence, all running locally without an API key.',categories:['Agent state','Human control','Grounding','Evaluation','Failure'],components:['20 live patterns','Evidence content','Human-control states']},
{name:'AI-native process artifacts',source:'Ayodhya Mohanthy',author:'Ayodhya Mohanthy',url:'/library',license:'Open copy-paste templates; cited primary sources',licenseUrl:'https://github.com/ayodhyamohanthy/ai-portfolio/blob/main/app/libraryData.ts',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Designer',use:'Seventeen fill-in templates for behavior, grounding, evals, failure, approval, handoff and interface decisions.',categories:['Grounding','Evaluation','Failure','Human control'],components:['Behavior spec','Grounding brief','Eval rubric','Failure taxonomy','Approval matrix','Handoff rule']},
{name:'Physics-based interaction components',source:'EasyUI',author:'Suraj Maurya',url:'https://www.easyui.site/components',license:'MIT',licenseUrl:'https://github.com/Surajmaurya1/easyui/blob/main/LICENSE',mode:'Hosted / MIT',reviewed:'30 Aug 2026',forWho:'Both',use:'Tactile motion primitives for interfaces that need clear state change, feedback and spatial continuity.',categories:['Motion','Navigation','Feedback','Human control'],components:['Magnetic button','Morphing dialog','Notification stack','Orbital loading','Command menu','Branching submenu']}
];
