'use client';
import Link from 'next/link';import {usePathname} from 'next/navigation';import {ReactNode} from 'react';import {freshFinds} from './freshData';import {cases} from './data';
import ThemeToggle from './ThemeToggle';
import XRightRail from './XRightRail';
import BrandMark from './BrandMark';
import {XIcon} from './XIcons';
const total=13+freshFinds.length+cases.length;
const folders=[['/','Home'],['/fresh','Explore'],['/system','Design system'],['/#cases','Case studies'],['/sources','Sources'],['/benchmarks','Benchmarks']];
const labels=[['/contact','Contact'],['/system','System map'],['/resources','Patterns'],['/components','Components'],['/library','Templates'],['/process','Process'],['/sources','Sources'],['/atlas','Atlas'],['/benchmarks','Benchmarks'],['/tools','Tools'],['/fresh','Fresh'],['/thinking','Thinking']];
function titleFor(path:string){if(path.startsWith('/work/'))return'Case study';return labels.find(([href])=>path===href||path.startsWith(`${href}/`))?.[1]||path.split('/').filter(Boolean)[0]||'Home'}
export default function RouteInbox({children}:{children:ReactNode}){const path=usePathname();if(path==='/')return <>{children}</>;const title=titleFor(path);return <div className="route-inbox"><header className="inbox-top"><button className="inbox-menu" aria-label="Open navigation">☰</button><BrandMark/><Link className="route-search" href="/">⌕ <span>Search Ayodhya’s work</span></Link><nav><Link href="/contact">Contact</Link><a href="https://github.com/ayodhyamohanthy/ai-portfolio">GitHub ↗</a><ThemeToggle/><i>AM</i></nav></header><div className="route-layout"><aside className="inbox-side"><Link className="compose route-back" href="/"><b>Message</b></Link><div className="mail-folders">{folders.map(([href,label])=><Link className={path===href?'active':''} href={href} key={href}><span><XIcon name={label==='Home'?'home':label==='Explore'?'search':label==='Case studies'?'article':label==='Benchmarks'?'chart':'system'}/></span>{label}</Link>)}</div><p>LABELS</p><div className="mail-labels">{labels.map(([href,label])=><Link className={path===href||path.startsWith(`${href}/`)?'active':''} key={href} href={href}><i/> {label}</Link>)}</div><footer><Link href="/resources/credits">Credits + licences</Link><Link href="/capabilities">Evidence</Link><Link href="/accessibility">Accessibility</Link></footer></aside><main className="route-pane"><div className="route-toolbar"><div><Link href="/" aria-label="Back to home"><XIcon name="back"/></Link><button aria-label="Like"><XIcon name="heart"/></button><button aria-label="Share"><XIcon name="share"/></button><button aria-label="More"><XIcon name="more"/></button></div><span>1 of {total}</span></div><article className="route-message-head"><div className="route-avatar">AM</div><div><span>{title.toUpperCase()}</span><h1>{title}</h1><p><b>Ayodhya Mohanthy</b> <i>@ayodhyamohanthy</i></p></div><time>AI-native product design</time></article><div className="route-content">{children}</div><div className="route-reply"><Link href="/">← Back to home</Link><Link href="/contact">Message Ayodhya</Link></div></main><XRightRail/></div><nav className="inbox-mobile-nav"><Link href="/"><i><XIcon name="home"/></i><span>Home</span></Link><Link href="/fresh"><i><XIcon name="search"/></i><span>Explore</span></Link><Link href="/system"><i><XIcon name="system"/></i><span>System</span></Link><Link href="/#cases"><i><XIcon name="article"/></i><span>Cases</span></Link><Link href="/benchmarks"><i><XIcon name="chart"/></i><span>Live</span></Link></nav></div>}
