'use client';
import Link from 'next/link';import {usePathname} from 'next/navigation';import {ReactNode} from 'react';import {freshFinds} from './freshData';import {cases} from './data';
import ThemeToggle from './ThemeToggle';
import Icon from './Icons';
const total=13+freshFinds.length+cases.length;
const folders=[['/','Inbox'],['/fresh','AI-native news'],['/system','Open design system'],['/#cases','Case studies'],['/sources','Learn AI-native design'],['/benchmarks','Live field']];
const labels=[['/contact','Contact'],['/system','System map'],['/resources','Patterns'],['/components','Components'],['/library','Templates'],['/process','Process'],['/sources','Sources'],['/atlas','Atlas'],['/benchmarks','Benchmarks'],['/tools','Tools'],['/fresh','Fresh'],['/thinking','Thinking']];
function titleFor(path:string){if(path.startsWith('/work/'))return'Case study';return labels.find(([href])=>path===href||path.startsWith(`${href}/`))?.[1]||path.split('/').filter(Boolean)[0]||'Inbox'}
export default function RouteInbox({children}:{children:ReactNode}){const path=usePathname();if(path==='/')return <>{children}</>;const title=titleFor(path);return <div className="route-inbox"><header className="inbox-top"><button className="inbox-menu" aria-label="Open navigation"><Icon name="menu"/></button><Link href="/" className="inbox-brand"><i>AM</i><span>Ayodhya</span><b>AI-native design</b></Link><Link className="route-search" href="/"><Icon name="search"/> <span>Search the design system</span></Link><nav><Link href="/contact">Contact</Link><a href="https://github.com/ayodhyamohanthy/ai-portfolio">GitHub ↗</a><ThemeToggle/><i>AM</i></nav></header><div className="route-layout"><aside className="inbox-side"><Link className="compose route-back" href="/"><Icon name="back"/> <b>Back to inbox</b></Link><div className="mail-folders">{folders.map(([href,label])=><Link className={path===href?'active':''} href={href} key={href}><span><Icon name={label==='Inbox'?'inbox':label==='AI-native news'?'news':label==='Case studies'?'case':label==='Learn AI-native design'?'learn':label==='Live field'?'live':'system'}/></span>{label}</Link>)}</div><p>LABELS</p><div className="mail-labels">{labels.map(([href,label])=><Link className={path===href||path.startsWith(`${href}/`)?'active':''} key={href} href={href}><i/> {label}</Link>)}</div><footer><Link href="/resources/credits">Credits + licences</Link><Link href="/capabilities">Evidence</Link><Link href="/accessibility">Accessibility</Link></footer></aside><main className="route-pane"><div className="route-toolbar"><div><Link href="/" aria-label="Back to inbox"><Icon name="back"/></Link><button aria-label="Archive"><Icon name="archive"/></button><button aria-label="Mark unread"><Icon name="mail"/></button><button aria-label="More"><Icon name="more"/></button></div><span>1 of {total}</span></div><article className="route-message-head"><div className="route-avatar">AM</div><div><span>{title.toUpperCase()}</span><h1>{title}</h1><p>Ayodhya Mohanthy <i>&lt;open@ayodhya.work&gt;</i></p></div><time>AI-native design system</time></article><div className="route-content">{children}</div><div className="route-reply"><Link href="/">← Back to inbox</Link><Link href="/contact">↩ Reply to Ayodhya</Link></div></main></div><nav className="inbox-mobile-nav"><Link href="/"><i><Icon name="inbox"/></i><span>Inbox</span></Link><Link href="/fresh"><i><Icon name="news"/></i><span>News</span></Link><Link href="/system"><i><Icon name="system"/></i><span>System</span></Link><Link href="/#cases"><i><Icon name="case"/></i><span>Cases</span></Link><Link href="/benchmarks"><i><Icon name="live"/></i><span>Live</span></Link></nav></div>}
