export type SourceItem={title:string;author:string;year:string;url:string;note:string};
export type SourceTrack={id:string;label:string;lede:string;items:SourceItem[]};
export const sourceTracks:SourceTrack[]=[
{id:'foundations',label:'Foundations',lede:'What AI-native design is, and why it is not a skin on old software.',items:[
{title:'Eight Dimensions of AI-Native Design',author:'Adam Kinney',year:'2026',url:'https://adamkinney.com/writing/eight-dimensions-of-ai-native-design/',note:'The cleanest break with the old frame: components become conversations, states become spectrums. My demos stream and blend instead of flipping for exactly this reason.'},
{title:'People + AI Guidebook',author:'Google PAIR',year:'2023',url:'https://pair.withgoogle.com/guidebook/',note:'The textbook. User needs, mental models, trust - less fashionable than the agent discourse and more useful when you actually ship.'}]},
{id:'interfaces',label:'Interfaces',lede:'How the surface changes when software acts on your behalf.',items:[
{title:'The Agent is the Interface',author:'Aaron Sagray',year:'2026',url:'https://sagray.com/articles/the-agent-is-the-interface',note:'Users evaluate an agent the way they evaluate a colleague - reliable, restrained, honest about what it did. Restraint as a design material. That one idea rewires a roadmap.'},
{title:'Designing Generative UI in an Agent-Native World',author:'Alice Moore · Builder.io',year:'2026',url:'https://www.builder.io/blog/designing-generative-ui-in-an-agent-native-world',note:'Generative UI is mainstream now. The design question is what stays fixed when the surface assembles itself - and the answer is grammar, not layout.'},
{title:'AI UX Patterns for AI-Native Products',author:'Lazarev.agency',year:'2026',url:'https://www.lazarev.agency/articles/ai-ux-patterns',note:'A pattern playbook with the right spine: show the reasoning, admit the uncertainty, hand control back. Closest to how I grade my own demos.'}]},
{id:'agents',label:'Agents',lede:'Your next user may not be human. Design for both readers.',items:[
{title:'Agent to UI: Designing Interfaces for AI Agents',author:'Richard Simms',year:'2026',url:'https://www.rsimms.com/stories/agent-to-ui',note:'An agent needs to know what a thing is, not what it looks like. The semantic contract under the pixels - most sites, mine included, are still catching up.'},
{title:'Dual-Native Design for the AI Future',author:'Lake Dai',year:'2026',url:'https://lakedai.substack.com/p/dual-native-design-for-the-ai-future',note:'Intuitive for people, structured for machines. Automated traffic has passed human traffic; be legible to both or illegible to one.'},
{title:'Agentic Design Systems Are Contracts, Not Libraries',author:'Tommaso Nervegna',year:'2026',url:'https://nervegna.substack.com/p/agentic-design-systems-are-contracts',note:'Most teams are quietly building the wrong half - the half that draws, not the half that promises. Read it before your next system audit.'}]},
{id:'cases',label:'Case studies',lede:'How shipped AI products actually got designed - told by the teams that built them.',items:[
{title:'Teaching agents product design at Vercel',author:'Vercel',year:'2026',url:'https://vercel.com/blog/teaching-agents-product-design-at-vercel',note:'Design governance becomes code: a repo skill routes judgment, linters enforce deterministic rules, evals test the guidance, and a weekly collector/judge/review-packet loop keeps human approval in charge. The operating metric matters: agents failed to invoke an available skill in 56% of Next.js evals, so trigger reliability must be tested separately from rule-following.'},
{title:'How Stripe built Kai: reusable skills and enterprise governance',author:'Sharadh Krishnamurthy / How I AI',year:'2026',url:'https://www.chatprd.ai/how-i-ai/how-stripe-built-kai-data-dashboards-reusable-skills-and-enterprise-ai-governance',note:'The leadership pattern is appropriate friction at scale: a named owner sets the models, skills, backends and approval rules for each project, while telemetry and deprecation keep a 2,000-skill ecosystem usable. Governance is product infrastructure, not a warning added at the end.'},
{title:'How we made our design system bilingual',author:'David Cai / BILL',year:'2026',url:'https://www.bill.com/engineering/how-we-made-our-design-system-bilingual',note:'One design truth, two delivery shapes: Storybook for people and structured CLI/MCP plus workflow skills for agents. The leadership move is the hard stop - if neither source can verify the system, the agent does not improvise frontend code.'},
{title:'Building products for humans and agents',author:'Tamar Yehoshua / Atlassian',year:'2026',url:'https://www.atlassian.com/blog/videos/atlassians-chief-ai-officer-on-building-products-for-humans-and-agents',note:'Treating agents as direct users makes design an operating-system problem: give them organizational context, keep a named human accountable across agent chains, and make inference spend a product decision. That is the leadership layer above any single AI interface.'},
{title:'When agents own the middle, design leads at the edges',author:'John Moriarty / Mind the Product',year:'2026',url:'https://www.mindtheproduct.com/how-fin-builds-at-the-edges-when-agents-own-the-middle-john-moriarty-at-mtpcon-london-2026/',note:'The useful leadership shift is not "designers code more." Design moves upstream into roadmap judgment and downstream into the shipped interface, while agents compress the execution middle. That is the operating shape I want this portfolio to prove.'},
{title:'How we built Linear Agent',author:'Matthijs Wolting · Linear',year:'2026',url:'https://linear.app/now/how-we-built-linear-agent',note:'Linear designed boundaries instead of paths: system prompt, tool design, run scope and the harness underneath are where the behaviour is shaped. Script it too tightly and you dilute the flexibility that makes an agent useful - the agent-design trade in one line.'},
{title:'Fin over email: How we built a multichannel AI agent',author:'Intercom Product & Design',year:'2026',url:'https://www.intercom.com/blog/fin-over-email-how-we-built/',note:'Intercom rebuilt Fin for email from first principles instead of porting the chat surface: an Intermission problem doc, an alpha with no bells, then iteration. The channel changes the contract - a case study in not copying your own pattern blindly.'},{title:'Building a Robust Harness for an Agent in Production',author:'Kamie Shami-Schnitzer · monday.com',year:'2026',url:'https://engineering.monday.com/building-a-robust-harness-for-agent-in-production-feed-agent-case-study/',note:'The bowling-bumper model of agent design: walk the flow, ask what can go wrong at each phase, build the guard there. The alias trick is the gem - swap raw IDs for aliases and every hallucinated citation becomes detectable instead of silent.'}]},
{id:'craft',label:'Craft',lede:'Pattern-level playbooks for the daily work.',items:[
{title:'Org Design for an AI-Native Design Org',author:'Aaron Sagray',year:'2026',url:'https://sagray.com/articles/org-design-for-an-ai-native-design-org',note:'Three accountable functions turn AI-native design into an operating model: skill librarian, eval owner and AgentOps. The draft RACI, fractional starting capacity, conversion thresholds, artifacts and cadences make the decision rights concrete enough to staff before they become full-time roles.'},
{title:'How to lead design teams through the AI era',author:'Jen Dunnam / Figma',year:'2026',url:'https://www.figma.com/blog/jen-dunnam-lead-design-teams/',note:'The leadership job is not to add panic to a team already moving fast. Steady the work, sharpen the principles, hire for dissent, and name which kind of speed matters before asking for more of it.'},
{title:'UX Patterns for Agentic AI: 16 Essentials',author:'Thiago Patriota',year:'2026',url:'https://library.thiagopatriota.com/blog/ux-patterns-for-agentic-ai-guide',note:'Sixteen patterns across delegate, steer, approve, interrupt, recover. The control-surface checklist alone is worth the read.'}]}];
