export type SourceItem={title:string;author:string;year:string;url:string;note:string};
export type SourceTrack={id:string;label:string;lede:string;items:SourceItem[]};
export const sourceTracks:SourceTrack[]=[
{id:'foundations',label:'Foundations',lede:'What AI-native design is, and why it is not a skin on old software.',items:[
{title:'Eight Dimensions of AI-Native Design',author:'Adam Kinney',year:'2026',url:'https://adamkinney.com/writing/eight-dimensions-of-ai-native-design/',note:'The cleanest break with the old frame: components become conversations, states become spectrums. My demos stream and blend instead of flipping for exactly this reason.'},
{title:'People + AI Guidebook',author:'Google PAIR',year:'2023',url:'https://pair.withgoogle.com/guidebook/',note:'The textbook. User needs, mental models, trust - less fashionable than the agent discourse and more useful when you actually ship.'}]},
{id:'interfaces',label:'Interfaces',lede:'How the surface changes when software acts on your behalf.',items:[
{title:'The Agent is the Interface',author:'Aaron Sagray',year:'2026',url:'https://sagray.com/articles/the-agent-is-the-interface',note:'Users evaluate an agent the way they evaluate a colleague - reliable, restrained, honest about what it did. Restraint as a design material. That one idea rewires a roadmap.'},
{title:'Designing Generative UI in an Agent-Native World',author:'Alice Moore · Builder.io',year:'2026',url:'https://www.builder.io/blog/designing-generative-ui-in-an-agent-native-world',note:'Generative UI is mainstream now. The design question is what stays fixed when the surface assembles itself - and the answer is grammar, not layout.'},
{title:'AI UX Patterns for AI-Native Products',author:'Lazarev.agency',year:'2026',url:'https://www.lazarev.agency/articles/ai-ux-patterns',note:'A pattern playbook with the right spine: show the reasoning, admit the uncertainty, hand control back. Closest to how I grade my own demos.'}]},
{id:'agents',label:'Agents',lede:'Your next user may not be human. Design for both readers.',items:[
{title:'Agent to UI: Designing Interfaces for AI Agents',author:'Richard Simms',year:'2026',url:'https://www.rsimms.com/stories/agent-to-ui',note:'An agent needs to know what a thing is, not what it looks like. The semantic contract under the pixels - most sites, mine included, are still catching up.'},
{title:'Govern the fleet as a product surface',author:'Karo Zieminski & ToxSec',year:'2026',url:'https://karozieminski.substack.com/p/agentic-fleet-governance-product-teams',note:'Once a team has several agents, the design object is the fleet. Give every agent an identity, owner, purpose, access boundary, review cadence and off switch. Make delegation preserve the initiating identity and pass only task-scoped authority with its own expiry. The control plane should answer what exists, who owns it, what it can reach, who it can call, what it did and how to stop it. Governance works when those answers are part of the build, not a document beside it.'},
{title:'Bind approval to the task revision',author:'Shengcheng Yu, Chunrong Fang & Zhenyu Chen',year:'2026',url:'https://arxiv.org/html/2609.11381',note:'An approval is not durable when the task keeps moving. Bind every effect to the exact task revision, referenced objects, role authority, operational controller and outcome evidence. When a person edits the shared application, a policy changes or a provider response arrives late, invalidate only the claims whose premises changed and ask again where needed. A correct component call can still compose into the wrong effect; continuous assurance belongs at the intent-to-effect boundary. This is a strong specification with worked examples, not yet evidence of production benefit.'},
{title:'Dual-Native Design for the AI Future',author:'Lake Dai',year:'2026',url:'https://lakedai.substack.com/p/dual-native-design-for-the-ai-future',note:'Intuitive for people, structured for machines. Automated traffic has passed human traffic; be legible to both or illegible to one.'},
{title:'Agentic Design Systems Are Contracts, Not Libraries',author:'Tommaso Nervegna',year:'2026',url:'https://nervegna.substack.com/p/agentic-design-systems-are-contracts',note:'Most teams are quietly building the wrong half - the half that draws, not the half that promises. Read it before your next system audit.'}]},
{id:'cases',label:'Case studies',lede:'How shipped AI products actually got designed - told by the teams that built them.',items:[
{title:'Design the interface for both readers',author:'Jin Gao / Affora',year:'2026',url:'https://arxiv.org/html/2609.19125',note:'Affora reverses the usual question. Instead of asking how an agent can cope with an interface built for people, it asks which interaction meanings the interface must preserve for both readers. The operating rule is substrate invariant, skin variable: keep controls, names, state, choices and outcomes explicit from component to site, while visual identity remains free to change. The checks are a conformance floor, not proof of task success.'},
{title:'Generate against approved objectives',author:'Gal Elidan & Yael Haramaty / Google Research',year:'2026',url:'https://research.google/blog/the-future-of-practice-enabling-teachers-to-create-learning-interactives-with-generative-ui/',note:'The strongest generative UI pipeline starts before generation and ends after it. Teachers approve the objectives; levels, hints and feedback derive from those objectives; agentic checks test pedagogy, mechanics, solvability and visual noise; and a teacher decides whether the result can enter the library. Dynamic UI becomes credible when authority, evaluation and publication gates are designed as one system.'},
{title:'Separate exploration from implementation',author:'Jian Zhao et al.',year:'2026',url:'https://arxiv.org/html/2609.15078',note:'Propose several structured design directions first; choose one explicitly; then hold downstream code generation fixed. This architecture makes exploration a controllable product decision instead of adding randomness to both aesthetics and syntax. The evaluation lesson matters just as much: measure coverage, rendered difference, adherence, execution, accessibility and human preference separately, because broader variation did not consistently mean better judged quality.'},
{title:'One design truth, three agent interfaces',author:'Sudharsanam Narasimhan, Kylor Hall & Michael Abrahamian / Atlassian',year:'2026',url:'https://www.atlassian.com/blog/ai-at-work/giving-ai-agents-design-system-context-from-the-terminal-what-we-learned-building-a-cli',note:'The important move is not adding a CLI. It is keeping one typed design truth behind skill, MCP and CLI, then judging the whole task instead of the payload. Atlassian held agent, model and tasks constant, read transcripts as well as metrics, and let observed behavior change routing, batching and follow-up guidance. Distribution stays flexible because governance does not fork.'},
{title:'Designing Grok Bot for a world of persistent agents',author:'SpaceXAI',year:'2026',url:'https://x.ai/news/designing-grok-bot',note:'I keep returning to the subtraction test: does this help someone delegate, or give them another surface to manage? Grok Bot uses that question to govern the whole system - persistent Bots instead of disposable chats, presence that shows state, graduated status/preview/takeover supervision, role-bound context, structured responses and routines that keep work moving. The useful lesson is coherence: primitives, coordination and autonomy all answer to the same product principle.'},
{title:'How Sierra’s design team keeps up with an engineering org 20x its size',author:'Designer Fund / Sierra',year:'2026',url:'https://designerfund.substack.com/p/ai-design-sierra',note:'Sierra’s leverage comes from refusing to become the 51st engineer. A tiny design team supports an engineering org nearly 20x its size by moving from individual polish to the systems, patterns and components that raise everyone’s floor, while keeping the judgment-building parts of craft deliberately human. Prototype against real data early; automate the infrastructure, not the taste.'},
{title:'Figma to Code at Scale: Building with Strands Agents',author:'Tim Moreton / Strands Agents',year:'2026',url:'https://strandsagents.com/blog/figma-to-code-at-scale-building-with-strands-agents/',note:'Amazon Ads turns Figma into production React across 20+ marketplaces with a governed agent team: specialists extract the design system, generate code, test overlap and overflow, research local constraints and measure quality. The leadership pattern is allocation by consequence - shared rules for every agent, the strongest model on code generation, deterministic checks on the rendered result, and measurement as a first-class role.'},
{title:'Inside the AI stack of Together AI’s product team',author:'Aakash Gupta / Together AI',year:'2026',url:'https://www.news.aakashg.com/p/together-ai-product-team',note:'The leadership asset is shared context, not a clever individual setup. Together AI gives every product area the same current context, encodes repeatable research and PRD work as team skills, and closes the loop with agent journeys that find product gaps, leave transcripts and re-verify the fix. AI-native product operations become collective memory plus continuous evidence.'},
{title:'Teaching agents product design at Vercel',author:'Vercel',year:'2026',url:'https://vercel.com/blog/teaching-agents-product-design-at-vercel',note:'Design governance becomes code: a repo skill routes judgment, linters enforce deterministic rules, evals test the guidance, and a weekly collector/judge/review-packet loop keeps human approval in charge. The operating metric matters: agents failed to invoke an available skill in 56% of Next.js evals, so trigger reliability must be tested separately from rule-following.'},
{title:'How Stripe built Kai: reusable skills and enterprise governance',author:'Sharadh Krishnamurthy / How I AI',year:'2026',url:'https://www.chatprd.ai/how-i-ai/how-stripe-built-kai-data-dashboards-reusable-skills-and-enterprise-ai-governance',note:'The leadership pattern is appropriate friction at scale: a named owner sets the models, skills, backends and approval rules for each project, while telemetry and deprecation keep a 2,000-skill ecosystem usable. Governance is product infrastructure, not a warning added at the end.'},
{title:'How we made our design system bilingual',author:'David Cai / BILL',year:'2026',url:'https://www.bill.com/engineering/how-we-made-our-design-system-bilingual',note:'One design truth, two delivery shapes: Storybook for people and structured CLI/MCP plus workflow skills for agents. The leadership move is the hard stop - if neither source can verify the system, the agent does not improvise frontend code.'},
{title:'Building products for humans and agents',author:'Tamar Yehoshua / Atlassian',year:'2026',url:'https://www.atlassian.com/blog/videos/atlassians-chief-ai-officer-on-building-products-for-humans-and-agents',note:'Treating agents as direct users makes design an operating-system problem: give them organizational context, keep a named human accountable across agent chains, and make inference spend a product decision. That is the leadership layer above any single AI interface.'},
{title:'When agents own the middle, design leads at the edges',author:'John Moriarty / Mind the Product',year:'2026',url:'https://www.mindtheproduct.com/how-fin-builds-at-the-edges-when-agents-own-the-middle-john-moriarty-at-mtpcon-london-2026/',note:'The useful leadership shift is not "designers code more." Design moves upstream into roadmap judgment and downstream into the shipped interface, while agents compress the execution middle. That is the operating shape I want this portfolio to prove.'},
{title:'How we built Linear Agent',author:'Matthijs Wolting · Linear',year:'2026',url:'https://linear.app/now/how-we-built-linear-agent',note:'Linear designed boundaries instead of paths: system prompt, tool design, run scope and the harness underneath are where the behaviour is shaped. Script it too tightly and you dilute the flexibility that makes an agent useful - the agent-design trade in one line.'},
{title:'Fin over email: How we built a multichannel AI agent',author:'Intercom Product & Design',year:'2026',url:'https://www.intercom.com/blog/fin-over-email-how-we-built/',note:'Intercom rebuilt Fin for email from first principles instead of porting the chat surface: an Intermission problem doc, an alpha with no bells, then iteration. The channel changes the contract - a case study in not copying your own pattern blindly.'},{title:'Building a Robust Harness for an Agent in Production',author:'Kamie Shami-Schnitzer · monday.com',year:'2026',url:'https://engineering.monday.com/building-a-robust-harness-for-agent-in-production-feed-agent-case-study/',note:'The bowling-bumper model of agent design: walk the flow, ask what can go wrong at each phase, build the guard there. The alias trick is the gem - swap raw IDs for aliases and every hallucinated citation becomes detectable instead of silent.'}]},
{id:'craft',label:'Craft',lede:'Pattern-level playbooks for the daily work.',items:[
{title:'Nad Chishtie: Lovable’s Design System for Agents',author:'Tommy Geoco / Lovable',year:'2026',url:'https://designertom.substack.com/p/nad-chishtie-lovables-design-system-147',note:'Lovable treats AI-native design as an org and governance problem, not a tool rollout. End-to-end ownership expands when everyone can build, while half the design system is written for agents. The useful failure is the leadership lesson: a two-week background-agent push did not hold, so the team kept the deterministic linters that did. Automate where the control is testable; kill the fashionable mechanism when it is not.'},
{title:'Crafting the last mile of delight',author:'Joel Lewenstein / IDEO',year:'2026',url:'https://www.ideo.com/journal/crafting-the-last-mile-of-delight',note:'When build time collapses, design leadership moves to the two ends: deciding what deserves to exist and protecting the last mile of quality. Anthropic’s 30-person design, research and content team makes that operating shift concrete - code-first prototypes in the middle, stronger judgment before and after, and agents enforcing routine content standards in production.'},
{title:'Org Design for an AI-Native Design Org',author:'Aaron Sagray',year:'2026',url:'https://sagray.com/articles/org-design-for-an-ai-native-design-org',note:'Three accountable functions turn AI-native design into an operating model: skill librarian, eval owner and AgentOps. The draft RACI, fractional starting capacity, conversion thresholds, artifacts and cadences make the decision rights concrete enough to staff before they become full-time roles.'},
{title:'How to lead design teams through the AI era',author:'Jen Dunnam / Figma',year:'2026',url:'https://www.figma.com/blog/jen-dunnam-lead-design-teams/',note:'The leadership job is not to add panic to a team already moving fast. Steady the work, sharpen the principles, hire for dissent, and name which kind of speed matters before asking for more of it.'},
{title:'UX Patterns for Agentic AI: 16 Essentials',author:'Thiago Patriota',year:'2026',url:'https://library.thiagopatriota.com/blog/ux-patterns-for-agentic-ai-guide',note:'Sixteen patterns across delegate, steer, approve, interrupt, recover. The control-surface checklist alone is worth the read.'}]}];
