export type SourceItem={title:string;author:string;year:string;url:string;note:string};
export type SourceTrack={id:string;label:string;lede:string;items:SourceItem[]};
export const sourceTracks:SourceTrack[]=[
{id:'foundations',label:'Foundations',lede:'What AI-native design is, and why it is not a skin on old software.',items:[
{title:'Eight Dimensions of AI-Native Design',author:'Adam Kinney',year:'2026',url:'https://adamkinney.com/writing/eight-dimensions-of-ai-native-design/',note:'The cleanest break with the old frame: components become conversations, states become spectrums. My demos stream and blend instead of flipping for exactly this reason.'},
{title:'People + AI Guidebook',author:'Google PAIR',year:'2023',url:'https://pair.withgoogle.com/guidebook/',note:'The textbook. User needs, mental models, trust - less fashionable than the agent discourse and more useful when you actually ship.'}]},
{id:'interfaces',label:'Interfaces',lede:'How the surface changes when software acts on your behalf.',items:[
{title:'The Agent is the Interface',author:'Aaron Sagray',year:'2026',url:'https://sagray.com/articles/the-agent-is-the-interface',note:'Users evaluate an agent the way they evaluate a colleague - reliable, restrained, honest about what it did. Restraint as a design material. That one idea rewires a roadmap.'},
{title:'Designing Generative UI in an Agent-Native World',author:'Alice Moore · Builder.io',year:'2026',url:'https://www.builder.io/blog/designing-generative-ui-in-an-agent-native-world',note:'Generative UI is mainstream now. The design question is what stays fixed when the surface assembles itself - and the answer is grammar, not layout.'},
{title:'AI UX Patterns for AI-Native Products',author:'Lazarev.agency',year:'2026',url:'https://www.lazarev.agency/articles/ai-ux-patterns',note:'A pattern playbook with the right spine: show the reasoning, admit the uncertainty, hand control back. Closest to how I grade my own demos.'}]},
{id:'agents',label:'Agents',lede:'Your next user may not be human. Design for both readers.',items:[
{title:'Agent to UI: Designing Interfaces for AI Agents',author:'Richard Simms',year:'2026',url:'https://www.rsimms.com/stories/agent-to-ui',note:'An agent needs to know what a thing is, not what it looks like. The semantic contract under the pixels - most sites, mine included, are still catching up.'},
{title:'Dual-Native Design for the AI Future',author:'Lake Dai',year:'2026',url:'https://lakedai.substack.com/p/dual-native-design-for-the-ai-future',note:'Intuitive for people, structured for machines. Automated traffic has passed human traffic; be legible to both or illegible to one.'},
{title:'Agentic Design Systems Are Contracts, Not Libraries',author:'Tommaso Nervegna',year:'2026',url:'https://nervegna.substack.com/p/agentic-design-systems-are-contracts',note:'Most teams are quietly building the wrong half - the half that draws, not the half that promises. Read it before your next system audit.'}]},
{id:'craft',label:'Craft',lede:'Pattern-level playbooks for the daily work.',items:[
{title:'UX Patterns for Agentic AI: 16 Essentials',author:'Thiago Patriota',year:'2026',url:'https://library.thiagopatriota.com/blog/ux-patterns-for-agentic-ai-guide',note:'Sixteen patterns across delegate, steer, approve, interrupt, recover. The control-surface checklist alone is worth the read.'}]}];
