export type ToolEntry={name:string;what:string;note:string;url:string;added:string;tags:string[]};
export const tools:ToolEntry[]=[
{name:'Design Words',what:'Browse design styles with live previews and copy the exact vocabulary as a prompt for your coding agent.',note:'Attacks a real gap: non-designers cannot tell an agent what they want because they lack the words for it.',url:'https://bensbites.com/design-words/',added:'13 Sep 2026',tags:['prompting','design-vocabulary']},
{name:'genieUI',what:'Visual workspace where AI composes interfaces strictly from your registered design-system components - editable and exportable, model-agnostic.',note:'The constraint is the product: the model selects and positions real components instead of emitting markup, so the output stays designable.',url:'https://genieui.com/',added:'12 Sep 2026',tags:['generative-ui','design-systems']},
{name:'Toolcraft',what:'Open-source starter kit and UI library for building custom design apps with an AI agent.',note:'Small tools shaped to your own workflow, built by the agent in your repo instead of rented from a platform. From Pixel Point, so the component craft is real - the agent starts from good material instead of generating its own.',url:'https://toolcraft.sh',added:'12 Sep 2026',tags:['Design tool','Open source']},
{name:'Frigade Assist API',what:'Tool call that lets an in-app agent answer with on-screen click guides instead of text.',note:'When no tool call exists for a task, most agents fall back to stale help-center RAG about their own product. Frigade learns the actual UI with a browser agent on a test account and returns a guide that points at the screen - the fallback becomes an interface instead of a paragraph.',url:'https://frigade.com/assist-api',added:'10 Sep 2026',tags:['Agents','Guides']},
{name:'json-render',what:'Generative UI framework by Vercel Labs - models emit JSON constrained to your component catalog.',note:'The guardrail is the point: the model can only assemble components you defined, so generative UI gets predictable enough to ship. One catalog renders to React, Vue, Svelte, React Native, even PDF and terminal - and the bundled shadcn set means the first render already looks like a real product.',url:'https://json-render.dev',added:'10 Sep 2026',tags:['Generation','Open source']},
{name:'v0',what:'Generative UI builder by Vercel - prompt to working React interface.',note:'The fastest way I know to make an interface idea tangible enough to judge. Output is real React and shadcn, so the throwaway draft is already close to the stack.',url:'https://v0.dev',added:'10 Sep 2026',tags:['Generation','Code']},
{name:'Subframe',what:'AI design tool that ships production React and Tailwind.',note:'Design with real components, wire your design system to AI agents, ship code. The closest thing to a design tool whose output is the product, not a picture of it.',url:'https://subframe.com',added:'10 Sep 2026',tags:['Design tool','Code']},
{name:'Onlook',what:'Open-source visual editor for running React apps - "Cursor for designers".',note:'Edit the live app visually and the code follows. Design and implementation stop being two files apart, which is where most handoff loss lives.',url:'https://onlook.com',added:'10 Sep 2026',tags:['Design tool','Open source']},
{name:'Figma AI',what:'Generation and first drafts inside Figma.',note:'AI where the layers stay editable. The canvas absorbs the model instead of handing you a flat image, so a generated draft can still be designed with.',url:'https://www.figma.com/ai/',added:'10 Sep 2026',tags:['Canvas','Generation']},
{name:'Relume',what:'AI sitemap, wireframe and marketing-site builder.',note:'Structure first, style later - the right order for AI-assisted page building. It behaves like a junior IA partner rather than a mockup printer.',url:'https://relume.io',added:'10 Sep 2026',tags:['Sites','Structure']},
{name:'Polymet',what:'AI product designer that drafts screens and prototypes from prompts.',note:'Useful for exploring directions before committing design time. Treat the output as a sketch to react to, not a decision to accept.',url:'https://www.polymet.ai',added:'10 Sep 2026',tags:['Generation','Prototyping']}];
