import Link from 'next/link';import {steps} from '../processData';import Reveal from '../Reveal';import CopyBlock from './CopyBlock';
export const metadata={title:'The Process · Ayodhya Mohanthy',description:'The AI-native design process, end to end. Seven steps from a one-line brief to a shipped design, with the exact tools and working templates.'};
export default function ProcessGuide(){return <main className="resource-page atlas-page fresh-page tools-page benchmarks-page process-guide-page">
<nav className="atlas-nav"><Link href="/" className="wordmark">Ayodhya Mohanthy</Link><div><Link href="/resources">Components</Link><Link href="/sources">Sources</Link><Link href="/atlas">Atlas</Link><Link href="/fresh">Fresh</Link><Link href="/tools">Tools</Link><Link href="/benchmarks">Benchmarks</Link><Link href="/thinking">Thinking</Link></div></nav>
<header className="atlas-hero"><p className="eyebrow">THE PROCESS · AI-NATIVE DESIGN</p><h1>From one line to a shipped design.<br/><i>Seven steps. Exact tools. Working templates.</i></h1><p>This is the whole process, written for someone who has never designed with AI before. Start at step 1 with nothing but an idea; end with something real that a stranger can use. Every tool is linked and verified live; every template is copy-paste ready. The philosophy behind it - what to delegate and what to never delegate - lives in <Link href="/process/ai-native">the companion essay</Link>.</p></header>
<section className="sources-track proc-overview" data-rv>
<div className="track-head"><b>MAP</b><div><h2>How the seven steps fit</h2><p>Brief and eval are the human half. Ground, diverge and converge are the conversation with the machine. Build and ship are where the work becomes real. Skipping a step is how AI projects turn into demos that impress nobody.</p></div></div>
<ol className="proc-map">{steps.map(s=><li key={s.n}><span>{s.n}</span><b>{s.name}</b><i>{s.claim}</i></li>)}</ol>
</section>
{steps.map(s=><section className="sources-track proc-step" key={s.n} data-rv>
<div className="track-head"><b>STEP {s.n}</b><div><h2>{s.name} · {s.claim}</h2><p>{s.body}</p></div></div>
<div className="proc-tools">{s.tools.map(t=>t.url.startsWith('/')?<Link key={t.name} href={t.url} className="proc-tool"><b>{t.name} ↗</b><span>{t.what}</span></Link>:<a key={t.name} href={t.url} target="_blank" rel="noopener noreferrer" className="proc-tool"><b>{t.name} ↗</b><span>{t.what}</span></a>)}</div>
<CopyBlock label={s.templateLabel} text={s.template}/>
<p className="proc-done"><span>DONE WHEN</span>{s.doneWhen}</p>
</section>)}
<section className="sources-track proc-close" data-rv>
<div className="track-head"><b>NEXT</b><div><h2>Then do it again</h2><p>The last line of your first run - where the stranger hesitated - is the first line of your second brief. That loop is the whole discipline. Everything else on this site is material for it: <Link href="/resources">74 live patterns</Link> to try in your browser, <Link href="/sources">the readings</Link> in order, <Link href="/benchmarks">the model rankings</Link> for choosing your tools, and <Link href="/process/ai-native">the rules I do not delegate</Link>.</p></div></div>
</section>
<footer className="resource-footer"><Link href="/">Ayodhya Mohanthy</Link><span>7 steps · {steps.reduce((a,s)=>a+s.tools.length,0)} tools · 7 templates · every tool link verified live 12 Sep 2026</span><a href="https://x.com/ayodhyamohanthy" target="_blank" rel="noopener noreferrer">Follow on X ↗</a><a href="https://www.linkedin.com/in/ayodhyamohanthy/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/ayodhyamohanthy" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://ayodhyamohanthy.substack.com" target="_blank" rel="noopener noreferrer">Newsletter ↗</a><Link href="/accessibility">Accessibility ↗</Link></footer><Reveal/></main>}
